import {readFile} from 'node:fs/promises';
import type {IncomingMessage,ServerResponse} from 'node:http';
import type {ArtifactStore,Data,Report} from './types.js';
import type {Billing} from './billing.js';
import type {Notifications} from './notifications.js';
import {AdminAccess,ADMIN_SESSION_MS} from './admin-access.js';
import {audit,digest,Operations} from './operations.js';
import {releaseReport} from './reports.js';

const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const date=(value?:number)=>value?new Date(value).toISOString().replace('T',' ').replace('.000Z',' UTC'):'Not available';
const style=`@font-face{font-family:Inter;font-style:normal;font-weight:400;font-display:swap;src:url('/admin/assets/inter-400.ttf')}@font-face{font-family:Inter;font-style:normal;font-weight:600;font-display:swap;src:url('/admin/assets/inter-600.ttf')}@font-face{font-family:Manrope;font-style:normal;font-weight:600;font-display:swap;src:url('/admin/assets/manrope-600.ttf')}@font-face{font-family:Manrope;font-style:normal;font-weight:700;font-display:swap;src:url('/admin/assets/manrope-700.ttf')}*{box-sizing:border-box}body{margin:0;background:#eff4f5;color:#425363;font:15px/1.55 Inter,Arial,sans-serif;overflow-wrap:anywhere}header{background:#0b1726;color:#fff;padding:18px}nav{display:flex;flex-wrap:wrap;gap:14px}nav a{color:#fff}main{max-width:1200px;margin:28px auto;padding:0 18px}h1,h2,h3{font-family:Manrope,Arial,sans-serif;color:#10263d}.card{background:#fff;border:1px solid #d2dfe2;border-radius:10px;padding:20px;margin:16px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,210px),1fr));gap:14px}.metric strong{display:block;font-size:1.8rem;color:#10263d}.warn{border-left:5px solid #d98b22}.danger{border-left:5px solid #b43b3b}.ok{border-left:5px solid #168678}table{width:100%;border-collapse:collapse;background:#fff}th,td{text-align:left;vertical-align:top;padding:10px;border-bottom:1px solid #d2dfe2}label{font-weight:600;display:block;margin-top:10px}input,select,textarea{width:100%;max-width:700px;padding:10px;border:1px solid #657887;border-radius:5px;font:inherit}textarea{min-height:90px}button{background:#168678;color:#fff;border:0;border-radius:5px;padding:10px 15px;font:inherit;cursor:pointer}.secondary{background:#566675}.danger-button{background:#9d3131}.actions{display:flex;flex-wrap:wrap;gap:10px;align-items:center}.actions form{display:inline}.muted{color:#657887}.evidence{white-space:pre-wrap;background:#f7f9fa;padding:12px;max-height:420px;overflow:auto}a{color:#116b60}a:focus-visible,button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid #10263d;outline-offset:3px}@media(max-width:650px){main{padding:0 10px;margin:18px auto}.card{padding:15px}table,thead,tbody,tr,th,td{display:block}thead{position:absolute;left:-9999px}td{padding:8px}td:before{content:attr(data-label);display:block;font-weight:700;color:#10263d}}`;
const shell=(title:string,content:string,csrf?:string)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | Regstead operator</title><style>${style}</style></head><body><header><nav aria-label="Operator navigation"><a href="/admin">Operator dashboard</a>${csrf?'<a href="/admin/organisations">Organisations</a><a href="/admin/onboard">Onboard</a><a href="/admin/review">Review queue</a><a href="/admin/reports">Reports</a><a href="/admin/billing">Billing</a><a href="/admin/operations">Operations</a>':''}</nav></header><main><h1>${esc(title)}</h1>${content}${csrf?`<form method="post" action="/admin/logout"><input type="hidden" name="csrf" value="${esc(csrf)}"><button class="secondary" type="submit">Sign out</button></form>`:''}</main></body></html>`;
const cookie=(name:string,value:string,maxAge:number)=>`${name}=${value}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`;
function cookies(req:IncomingMessage){const result:Record<string,string>={};for(const part of (req.headers.cookie??'').split(';')){const [key,...value]=part.trim().split('=');if(key)result[key]=value.join('=');}return result;}
function latestSubscription(data:Data,organisationId:string){return data.subscriptions.filter(s=>s.organisationId===organisationId).at(-1);}
function latestReview(data:Data,reportId:string,findingId:string){return data.reviews.filter(r=>r.reportId===reportId&&r.findingId===findingId).at(-1);}
export function pilotMetrics(data:Data,now=Date.now()){
  const durations=data.runs.map(r=>Date.parse(r.completedAt)-Date.parse(r.startedAt)).filter(n=>Number.isFinite(n)&&n>=0),released=data.reports.filter(r=>r.releasedAt),turnarounds=released.map(r=>r.releasedAt!-r.createdAt),decisions=data.reviews.filter(r=>data.reports.some(report=>report.id===r.reportId));
  const average=(values:number[])=>values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length):0;
  return {scanCount:data.runs.length,averageScanDurationMs:average(durations),averageReviewTurnaroundMs:average(turnarounds),findingsReviewed:new Set(decisions.map(r=>r.reportId+':'+r.findingId)).size,approved:decisions.filter(r=>r.status==='APPROVED').length,suppressed:decisions.filter(r=>r.status==='SUPPRESSED').length,annotated:decisions.filter(r=>r.status==='ANNOTATED').length,emailAccepted:data.notifications.filter(n=>n.status==='SENT').length,emailFailed:data.notifications.filter(n=>n.status==='FAILED').length,jobFailures:data.jobs.filter(j=>j.status==='FAILED').length,jobRetries:data.jobs.reduce((sum,j)=>sum+j.retryCount,0),overdueSchedules:data.sites.filter(s=>s.active&&!s.paused&&s.nextRunAt<now).length};
}
export class AdminPortal {
  constructor(readonly access:AdminAccess,private operations:Operations,private storage:ArtifactStore,private billing:Billing|undefined,private notifications:Notifications,private ready:()=>Promise<unknown>,private trustedProxyAddress?:string,private now=Date.now){}
  private headers(res:ServerResponse){res.setHeader('Cache-Control','no-store, private');res.setHeader('Referrer-Policy','strict-origin');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Strict-Transport-Security','max-age=31536000');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Content-Security-Policy',`default-src 'none'; font-src 'self'; style-src 'sha256-${Buffer.from(digest(style),'hex').toString('base64')}'; base-uri 'none'; form-action 'self' https://billing.stripe.com; frame-ancestors 'none'`);}
  private html(res:ServerResponse,body:string,status=200){res.statusCode=status;res.setHeader('Content-Type','text/html; charset=utf-8');res.end(body);}
  private redirect(res:ServerResponse,to:string){if(!to.startsWith('/admin')&&!/^https:\/\/billing\.stripe\.com\//.test(to))throw new Error('Invalid redirect');res.statusCode=303;res.setHeader('Location',to);res.end();}
  private async form(req:IncomingMessage){if(!req.headers['content-type']?.startsWith('application/x-www-form-urlencoded'))throw new Error('Invalid request');const chunks:Buffer[]=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>32768)throw new Error('Invalid request');chunks.push(Buffer.from(chunk));}return new URLSearchParams(Buffer.concat(chunks).toString());}
  private csrf(csrf:string){return `<input type="hidden" name="csrf" value="${esc(csrf)}">`;}
  async handle(req:IncomingMessage,res:ServerResponse):Promise<boolean>{if(!req.url?.startsWith('/admin'))return false;this.headers(res);try{const origin=new URL(this.access.origin);if(req.headers.host!==origin.host)throw new Error('Invalid host');const directTLS=!!(req.socket as {encrypted?:boolean}).encrypted,proxyTLS=this.trustedProxyAddress&&req.socket.remoteAddress===this.trustedProxyAddress&&req.headers['x-forwarded-proto']==='https';if(!directTLS&&!proxyTLS)throw new Error('HTTPS required');if(req.method==='POST'&&req.headers.origin!==this.access.origin)throw new Error('Invalid origin');const url=new URL(req.url,this.access.origin),path=url.pathname,c=cookies(req),client=req.socket.remoteAddress??'unknown';
      if(req.method==='GET'&&/^\/admin\/assets\/(inter-(400|600)|manrope-(600|700))\.ttf$/.test(path)){res.setHeader('Content-Type','font/ttf');res.end(await readFile(new URL('../../assets/portal/'+path.split('/').at(-1),import.meta.url)));return true;}
      if(req.method==='GET'&&(path==='/admin/login'||path==='/admin/auth/verify')){await this.access.limit('form:'+client,60);const csrf=await this.access.form();res.setHeader('Set-Cookie',cookie('__Host-regstead-admin-form',csrf,900));const verify=path.endsWith('/verify'),fields=verify?`<p>Confirm this private operator sign-in.</p><input type="hidden" name="token" value="${esc(url.searchParams.get('token')??'')}">`:'<label for="email">Operator email</label><input id="email" name="email" type="email" autocomplete="email" required maxlength="254"><p>Only pre-authorised operators receive a link.</p>';this.html(res,shell(verify?'Confirm operator sign-in':'Operator sign-in',`<section class="card"><form method="post" action="${verify?'/admin/auth/verify':'/admin/login'}">${this.csrf(csrf)}${fields}<button type="submit">${verify?'Sign in':'Email operator link'}</button></form></section>`));return true;}
      if(req.method==='POST'&&(path==='/admin/login'||path==='/admin/auth/verify')){const form=await this.form(req);await this.access.consumeForm(form.get('csrf')??'',c['__Host-regstead-admin-form']??'');if(path==='/admin/login'){try{await this.access.request(form.get('email')??'',client);}catch{}this.html(res,shell('Check your email','<p>If this operator is authorised and within rate limits, a single-use link will arrive shortly.</p>'));return true;}const session=await this.access.verify(form.get('token')??'',client,c['__Host-regstead-admin-session']);res.setHeader('Set-Cookie',[cookie('__Host-regstead-admin-session',session.session,ADMIN_SESSION_MS/1000),cookie('__Host-regstead-admin-csrf',session.csrf,ADMIN_SESSION_MS/1000),cookie('__Host-regstead-admin-form','',0)]);this.redirect(res,'/admin');return true;}
      let context;try{context=await this.access.authenticate(c['__Host-regstead-admin-session']??'');}catch{this.redirect(res,'/admin/login');return true;}const {data,user}=context,csrf=c['__Host-regstead-admin-csrf']??'',session=c['__Host-regstead-admin-session'];
      if(req.method==='POST'){const form=await this.form(req);await this.access.csrf(session,form.get('csrf')??'');const actor=user.displayName+' ['+user.id+']';if(path==='/admin/logout'){await this.access.logout(session,form.get('csrf')??'');res.setHeader('Set-Cookie',[cookie('__Host-regstead-admin-session','',0),cookie('__Host-regstead-admin-csrf','',0)]);this.redirect(res,'/admin/login');return true;}
        if(path==='/admin/onboard'){if(form.get('packConfirmed')!=='yes')throw new Error('Pack confirmation required');await this.operations.onboard({legalName:form.get('legalName')??'',displayName:form.get('displayName')||undefined,contactName:form.get('contactName')??'',contactEmail:form.get('contactEmail')??'',url:form.get('url')??'',notes:form.get('notes')||undefined,cadenceMs:Number(form.get('cadenceMs')),browserFallback:form.get('browserFallback')==='yes',pack:'lawwatch-england-wales',packConfirmed:true,sectorApplicability:form.get('sectorApplicability') as 'ESTABLISHED'|'NOT_ESTABLISHED'},actor);this.redirect(res,'/admin/organisations');return true;}
        let match=/^\/admin\/review\/([\w-]+)\/([\w-]+)$/.exec(path);if(match){await this.operations.review(match[1],match[2],form.get('status') as 'APPROVED',form.get('note')??'',actor,form.get('title')||undefined,form.get('explanation')||undefined);this.redirect(res,'/admin/review/'+match[1]);return true;}
        match=/^\/admin\/reports\/([\w-]+)\/release$/.exec(path);if(match){if(form.get('confirm')!=='RELEASE')throw new Error('Release confirmation required');await releaseReport(this.access.repository,this.storage,match[1],actor,this.now());this.redirect(res,'/admin/reports');return true;}
        match=/^\/admin\/sites\/([\w-]+)\/(pause|resume)$/.exec(path);if(match){await this.operations.pause(match[1],match[2]==='pause',actor);this.redirect(res,'/admin/organisations');return true;}
        match=/^\/admin\/jobs\/([\w-]+)\/retry$/.exec(path);if(match){await this.operations.retry(match[1],actor);this.redirect(res,'/admin');return true;}
        match=/^\/admin\/webhooks\/([\w-]+)\/retry$/.exec(path);if(match){if(!this.billing)throw new Error('Billing unavailable');await this.billing.retry(match[1],actor);this.redirect(res,'/admin');return true;}
        match=/^\/admin\/notifications\/([\w-]+)\/retry$/.exec(path);if(match){await this.notifications.retry(match[1],actor);this.redirect(res,'/admin');return true;}
        match=/^\/admin\/billing\/([\w-]+)\/manage$/.exec(path);if(match){if(!this.billing)throw new Error('Billing unavailable');const to=await this.billing.billingPortal(match[1]);if(new URL(to).origin!=='https://billing.stripe.com')throw new Error('Invalid redirect');await this.access.repository.transaction(d=>audit(d,'operator_billing_portal_opened',this.now(),{organisationId:match![1],actor}));this.redirect(res,to);return true;}
        this.html(res,shell('Not found','<p>Mutation unavailable.</p>',csrf),404);return true;
      }
      if(req.method!=='GET'){this.html(res,shell('Not found','<p>Page unavailable.</p>',csrf),404);return true;}const fresh=await this.access.repository.read();
      if(path==='/admin'){const state=await this.ready() as Record<string,unknown>,counts=Object.fromEntries(['QUEUED','RUNNING','AWAITING_REVIEW','FAILED'].map(status=>[status,fresh.jobs.filter(j=>j.status===status).length])),metrics=pilotMetrics(fresh,this.now()),subscriptions=fresh.organisations.map(o=>latestSubscription(fresh,o.id)).filter(Boolean);this.html(res,shell('Pilot operations',`<section class="grid">${Object.entries({...counts,unreleased:fresh.reports.filter(r=>r.status==='DRAFT').length,activeSubscriptions:subscriptions.filter(s=>s?.status==='active').length,paymentIssues:subscriptions.filter(s=>s?.status==='past_due').length,cancelledSubscriptions:subscriptions.filter(s=>s?.status==='cancelled').length,failedWebhooks:fresh.webhooks.filter(w=>w.status==='FAILED').length,failedEmails:fresh.notifications.filter(n=>n.status==='FAILED').length}).map(([k,v])=>`<div class="card metric"><span>${esc(k)}</span><strong>${v}</strong></div>`).join('')}</section><section class="card ${state.ready?'ok':'danger'}"><h2>System readiness</h2><pre>${esc(JSON.stringify(state,null,2))}</pre><p>Worker heartbeat: ${esc(date(fresh.heartbeats.worker))}</p></section><section class="card"><h2>Pilot metrics</h2><dl>${Object.entries(metrics).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl></section><section class="card"><h2>Next monitoring runs</h2>${fresh.sites.sort((a,b)=>a.nextRunAt-b.nextRunAt).map(s=>`<p><a href="/admin/organisations/${s.organisationId}">${esc(s.hostname)}</a>: ${esc(date(s.nextRunAt))}${s.paused?' (paused)':''}</p>`).join('')||'<p>None.</p>'}</section>`,csrf));return true;}
      if(path==='/admin/onboard'){this.html(res,shell('Onboard pilot organisation',`<section class="card warn"><p><strong>Pack safeguard:</strong> LawWatch England & Wales must be explicitly selected. Confirm whether sector applicability has been established. NOT ESTABLISHED is allowed for investigation but remains visibly warned and must not be presented as legal applicability.</p></section><form class="card" method="post" action="/admin/onboard">${this.csrf(csrf)}<label>Legal name<input name="legalName" required></label><label>Display name<input name="displayName"></label><label>Contact name<input name="contactName" required></label><label>Contact email<input name="contactEmail" type="email" required></label><label>Primary website<input name="url" type="url" required></label><label>Pack<select name="pack" disabled><option>LawWatch England & Wales</option></select></label><label>Sector applicability<select name="sectorApplicability" required><option value="">Choose after checking</option><option value="ESTABLISHED">Established</option><option value="NOT_ESTABLISHED">Not established — warning retained</option></select></label><label><input name="packConfirmed" value="yes" type="checkbox" required> I explicitly confirm assignment of lawwatch-england-wales</label><label>Cadence milliseconds<input name="cadenceMs" type="number" min="3600000" value="86400000" required></label><label><input name="browserFallback" value="yes" type="checkbox"> Permit selective browser fallback</label><label>Operator notes<textarea name="notes"></textarea></label><button type="submit">Create organisation and baseline</button></form>`,csrf));return true;}
      if(path==='/admin/organisations'){const rows=fresh.organisations.map(org=>{const site=fresh.sites.find(s=>s.organisationId===org.id),sub=latestSubscription(fresh,org.id),last=fresh.reports.filter(r=>r.organisationId===org.id&&r.status==='RELEASED').at(-1);return `<tr><td data-label="Organisation"><a href="/admin/organisations/${org.id}">${esc(org.displayName)}</a></td><td data-label="Website">${esc(site?.hostname)}</td><td data-label="Pack">${esc(site?.pack)}<br>${esc(site?.sectorApplicability??'LEGACY UNCONFIRMED')}</td><td data-label="Monitoring">${site?.paused?'Paused':site?.active?'Active':'Inactive'}</td><td data-label="Subscription">${esc(sub?.status??'None')}</td><td data-label="Latest report">${esc(date(last?.releasedAt))}</td></tr>`;}).join('');this.html(res,shell('Organisations',`<table><thead><tr><th>Organisation</th><th>Website</th><th>Pack</th><th>Monitoring</th><th>Subscription</th><th>Latest report</th></tr></thead><tbody>${rows}</tbody></table>`,csrf));return true;}
      if(path==='/admin/billing'){const rows=fresh.organisations.map(org=>{const sub=latestSubscription(fresh,org.id);return `<tr><td data-label="Organisation"><a href="/admin/organisations/${org.id}">${esc(org.displayName)}</a></td><td data-label="Status">${esc(sub?.status??'No subscription')}</td><td data-label="Period end">${esc(date(sub?.currentPeriodEnd))}</td><td data-label="Cancellation">${sub?.cancelAtPeriodEnd?'At period end':'No period-end cancellation recorded'}</td><td data-label="Grace deadline">${esc(date(sub?.graceDeadline))}</td><td data-label="Action">${sub?`<form method="post" action="/admin/billing/${org.id}/manage">${this.csrf(csrf)}<button>Open Stripe Billing Portal</button></form>`:'None'}</td></tr>`;}).join('');this.html(res,shell('Billing',`<section class="card warn"><p>Verified Stripe webhooks remain authoritative. Provider identifiers are deliberately hidden.</p></section><table><thead><tr><th>Organisation</th><th>Status</th><th>Period end</th><th>Cancellation</th><th>Grace deadline</th><th>Action</th></tr></thead><tbody>${rows}</tbody></table>`,csrf));return true;}
      if(path==='/admin/operations'){const jobs=fresh.jobs.filter(j=>['QUEUED','RUNNING','FAILED'].includes(j.status)).map(j=>`<tr><td data-label="Type">${esc(j.type)}</td><td data-label="Status">${esc(j.status)}</td><td data-label="Scheduled">${esc(date(j.scheduledAt))}</td><td data-label="Failure">${esc(j.failureCode??'None')}</td><td data-label="Action">${j.status==='FAILED'?`<form method="post" action="/admin/jobs/${j.id}/retry">${this.csrf(csrf)}<button>Retry eligible job</button></form>`:'None'}</td></tr>`).join(''),webhooks=fresh.webhooks.filter(w=>w.status==='FAILED').map(w=>`<p>${esc(w.type)} · ${esc(w.failureCode??'No failure code')} <form method="post" action="/admin/webhooks/${w.id}/retry">${this.csrf(csrf)}<button>Retry webhook</button></form></p>`).join(''),emails=fresh.notifications.filter(n=>n.status==='FAILED').map(n=>`<p>${esc(n.template)} · ${esc(n.failureCode??'No failure code')} <form method="post" action="/admin/notifications/${n.id}/retry">${this.csrf(csrf)}<button>Retry email</button></form></p>`).join('');this.html(res,shell('Operations',`<section class="card"><h2>Worker state</h2><p>Heartbeat: ${esc(date(fresh.heartbeats.worker))}</p></section><section class="card"><h2>Current and failed jobs</h2><table><thead><tr><th>Type</th><th>Status</th><th>Scheduled</th><th>Failure</th><th>Action</th></tr></thead><tbody>${jobs}</tbody></table>${jobs?'':'<p>No queued, running or failed jobs.</p>'}</section><section class="card"><h2>Failed webhooks</h2>${webhooks||'<p>None.</p>'}</section><section class="card"><h2>Failed email deliveries</h2>${emails||'<p>None.</p>'}</section>`,csrf));return true;}
      let match=/^\/admin\/organisations\/([\w-]+)$/.exec(path);if(match){const org=fresh.organisations.find(o=>o.id===match![1]);if(org){const site=fresh.sites.find(s=>s.organisationId===org.id)!,sub=latestSubscription(fresh,org.id),jobs=fresh.jobs.filter(j=>j.organisationId===org.id),reports=fresh.reports.filter(r=>r.organisationId===org.id&&r.status==='RELEASED');this.html(res,shell(org.displayName,`<section class="card"><dl><dt>Legal identity</dt><dd>${esc(org.legalName)}</dd><dt>Contact</dt><dd>${esc(org.contactName)} · ${esc(org.contactEmail)}</dd><dt>Primary website</dt><dd>${esc(site.hostname)}</dd><dt>Pack</dt><dd>${esc(site.pack)}</dd><dt>Pack confirmation</dt><dd>${esc(site.sectorApplicability??'Legacy site — confirmation not recorded')} · ${esc(date(site.packConfirmedAt))}</dd><dt>Monitoring</dt><dd>${site.paused?'Paused':site.active?'Active':'Inactive'}</dd><dt>Subscription</dt><dd>${esc(sub?.status??'None')} ${sub?.cancelAtPeriodEnd?'· cancels at period end':''} · period end ${esc(date(sub?.currentPeriodEnd))}</dd><dt>Latest scan</dt><dd>${esc(date(site.lastSuccessfulRunAt))}</dd><dt>Latest released report</dt><dd>${esc(date(reports.at(-1)?.releasedAt))}</dd></dl><div class="actions"><form method="post" action="/admin/sites/${site.id}/${site.paused?'resume':'pause'}">${this.csrf(csrf)}<button>${site.paused?'Resume':'Pause'} monitoring</button></form>${sub?`<form method="post" action="/admin/billing/${org.id}/manage">${this.csrf(csrf)}<button class="secondary">Open Stripe Billing Portal</button></form>`:''}</div></section><section class="card"><h2>Jobs</h2>${jobs.map(j=>`<p>${esc(j.type)} · ${esc(j.status)} · ${esc(date(j.scheduledAt))}${j.status==='FAILED'?` <form method="post" action="/admin/jobs/${j.id}/retry">${this.csrf(csrf)}<button>Retry eligible job</button></form>`:''}</p>`).join('')}</section>`,csrf));return true;}}
      if(path==='/admin/review'){const drafts=fresh.reports.filter(r=>r.status==='DRAFT');this.html(res,shell('Review queue',drafts.map(r=>{const values=(key:'status'|'severity'|'confidence')=>Object.fromEntries([...new Set(r.findings.map(f=>String((f.raw as unknown as Record<string,unknown>)[key]??'not supplied')))].map(value=>[value,r.findings.filter(f=>String((f.raw as unknown as Record<string,unknown>)[key]??'not supplied')===value).length]));return `<article class="card"><h2><a href="/admin/review/${r.id}">${esc(fresh.organisations.find(o=>o.id===r.organisationId)?.displayName)}</a></h2><p>${esc(r.id)} · ${esc(date(r.createdAt))}</p><p><strong>Raw status:</strong> ${esc(JSON.stringify(values('status')))}</p><p><strong>Severity:</strong> ${esc(JSON.stringify(values('severity')))}</p><p><strong>Confidence:</strong> ${esc(JSON.stringify(values('confidence')))}</p></article>`;}).join('')||'<p>No reports await review.</p>',csrf));return true;}
      match=/^\/admin\/review\/([\w-]+)$/.exec(path);if(match){const report=fresh.reports.find(r=>r.id===match![1]&&r.status==='DRAFT');if(report){const run=fresh.runs.find(r=>r.id===report.scanRunId),org=fresh.organisations.find(o=>o.id===report.organisationId),first=!run?.comparisonBaseline;const findings=report.findings.map(f=>{const previous=latestReview(fresh,report.id,f.id),raw=f.raw as typeof f.raw&{confidence?:string;applicability?:string;serviceType?:string;resource?:string;unknownReasonCodes?:string[]};return `<article class="card ${raw.status==='POTENTIAL_ISSUE'?'danger':raw.status==='UNKNOWN'?'warn':''}"><h3>${esc(raw.ruleId)} v${esc(raw.ruleVersion)} — ${esc(f.title)}</h3><p><strong>${esc(raw.status)}</strong> · severity ${esc(raw.severity)} · confidence ${esc(raw.confidence??'not supplied')} · applicability ${esc(raw.applicability??'not supplied')}</p><p>Service context: ${esc(raw.serviceType??'firm-wide/site')}</p><p>${esc(f.explanation)}</p><p>Resource: ${esc(raw.resource??'not supplied')}</p><details><summary>Evidence and comparison context</summary><pre class="evidence">${esc(JSON.stringify({comparisonBaseline:run?.comparisonBaseline,unknownReasonCodes:raw.unknownReasonCodes,evidence:raw.evidence},null,2).slice(0,12000))}</pre></details>${previous?`<p>Latest decision: <strong>${esc(previous.status)}</strong> by ${esc(previous.reviewer)} — ${esc(previous.note)}</p>`:''}<form method="post" action="/admin/review/${report.id}/${f.id}">${this.csrf(csrf)}<label>Decision<select name="status" required><option value="">Choose individually</option><option>APPROVED</option><option>SUPPRESSED</option><option>ANNOTATED</option></select></label><label>Audit note<textarea name="note" required></textarea></label><label>Customer title for annotation<input name="title"></label><label>Customer explanation for annotation<textarea name="explanation"></textarea></label><button type="submit">Record this finding decision</button></form></article>`;}).join('');const complete=report.findings.every(f=>latestReview(fresh,report.id,f.id));this.html(res,shell(`Review ${org?.displayName??report.id}`,`${first?'<section class="card warn"><strong>First baseline:</strong> no previous comparison baseline exists. Continuity checks retain their raw UNKNOWN or NOT_APPLICABLE state and require context-aware review.</section>':''}<p>${report.findings.length} findings. Decisions are individual and append-only.</p>${findings}${complete?`<section class="card danger"><h2>Release confirmation</h2><p>Confirm all evidence and customer wording before freezing the immutable artifact.</p><form method="post" action="/admin/reports/${report.id}/release">${this.csrf(csrf)}<label>Type RELEASE<input name="confirm" required></label><button class="danger-button">Release reviewed report</button></form></section>`:'<p class="card warn">Release remains blocked until every finding has a decision.</p>'}`,csrf));return true;}}
      if(path==='/admin/reports'){const reports=fresh.reports.filter(r=>r.status==='RELEASED').sort((a,b)=>b.releasedAt!-a.releasedAt!);this.html(res,shell('Released reports',reports.map(r=>`<article class="card"><h2>${esc(fresh.organisations.find(o=>o.id===r.organisationId)?.displayName)}</h2><p>${esc(r.id)} · released ${esc(date(r.releasedAt))}</p><p>SHA-256: ${esc(r.hash)}</p><div class="actions"><a href="/admin/reports/${r.id}">View customer artifact</a><a href="/admin/reports/${r.id}/download">Download</a></div></article>`).join('')||'<p>No reports released.</p>',csrf));return true;}
      match=/^\/admin\/reports\/([\w-]+)(\/download)?$/.exec(path);if(match){const report=fresh.reports.find(r=>r.id===match![1]&&r.status==='RELEASED'&&r.artifact&&r.hash);if(report){const bytes=await this.storage.get(report.artifact!);if(digest(bytes)!==report.hash)throw new Error('Report integrity failure');res.setHeader('Content-Security-Policy',"sandbox; default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'");res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Content-Disposition',`${match[2]?'attachment':'inline'}; filename="regstead-report-${report.id}.html"`);res.end(bytes);return true;}}
      this.html(res,shell('Not found','<p>Operator page unavailable.</p>',csrf),404);return true;
    }catch{this.html(res,shell('Request unavailable','<p>The request could not be completed. Return to <a href="/admin/login">operator sign-in</a>.</p>'),400);return true;}}
}
