import {randomBytes,timingSafeEqual} from 'node:crypto';
import type {Data,EmailProvider,OperatorUser,Repository} from './types.js';
import {audit,digest,id,required} from './operations.js';

export const ADMIN_LINK_MS=15*60_000,ADMIN_SESSION_MS=4*3600_000;
const secret=()=>randomBytes(32).toString('base64url');
const equal=(a:string,b:string)=>timingSafeEqual(Buffer.from(a),Buffer.from(b));

export class AdminAccess {
  constructor(readonly repository:Repository,private email:EmailProvider,readonly origin:string,private now=Date.now){const url=new URL(origin);if(url.protocol!=='https:'||url.origin!==origin)throw new Error('Admin requires an HTTPS origin');}
  async create(email:string,displayName:string,actor:string){actor=required(actor,100);email=email.trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254)throw new Error('Invalid email');required(displayName,100);return this.repository.transaction(d=>{if(d.operatorUsers.some(u=>u.email===email))throw new Error('Operator already authorised');const user:OperatorUser={id:id(),email,displayName,role:'ADMIN',status:'ACTIVE',createdAt:this.now(),updatedAt:this.now()};d.operatorUsers.push(user);audit(d,'operator_user_created',this.now(),{actor,code:user.id});return user;});}
  async disable(userId:string,actor:string){actor=required(actor,100);await this.repository.transaction(d=>{const user=d.operatorUsers.find(u=>u.id===userId);if(!user)throw new Error('Unknown operator');user.status='DISABLED';user.updatedAt=this.now();d.operatorSessions=d.operatorSessions.filter(s=>s.userId!==userId);for(const link of d.operatorLinks.filter(l=>l.userId===userId))link.usedAt=this.now();audit(d,'operator_user_disabled',this.now(),{actor,code:user.id});});}
  private prune(d:Data){const now=this.now();d.portalRates=d.portalRates.filter(r=>r.expiresAt>now);d.portalForms=d.portalForms.filter(f=>f.expiresAt>now);d.operatorSessions=d.operatorSessions.filter(s=>s.expiresAt>now);d.operatorLinks=d.operatorLinks.filter(l=>l.expiresAt>now);}
  async limit(key:string,max:number,windowMs=15*60_000){const allowed=await this.repository.transaction(d=>{this.prune(d);const hash=digest('admin:'+key);let rate=d.portalRates.find(r=>r.id===hash);if(!rate){if(d.portalRates.length>=10000)return false;rate={id:hash,count:0,expiresAt:this.now()+windowMs};d.portalRates.push(rate);}rate.count++;return rate.count<=max;});if(!allowed)throw new Error('Rate limited');}
  async form(){const token=secret();await this.repository.transaction(d=>{this.prune(d);if(d.portalForms.length>=10000)throw new Error('Rate limited');d.portalForms.push({id:digest('admin:'+token),expiresAt:this.now()+ADMIN_LINK_MS});});return token;}
  async consumeForm(token:string,cookie:string){if(!token||!cookie||!equal(digest(token),digest(cookie)))throw new Error('Invalid request');await this.repository.transaction(d=>{const index=d.portalForms.findIndex(f=>f.id===digest('admin:'+token)&&f.expiresAt>this.now());if(index<0)throw new Error('Invalid request');d.portalForms.splice(index,1);});}
  async invite(userId:string,actor:string){required(actor,100);const user=(await this.repository.read()).operatorUsers.find(u=>u.id===userId&&u.status==='ACTIVE');if(!user)throw new Error('Unavailable operator');await this.request(user.email,'operator:'+actor);}
  async request(email:string,client:string){await this.limit('login-ip:'+client,20);email=email.trim().toLowerCase();await this.limit('login-email:'+email,3);const token=secret();const delivery=await this.repository.transaction(d=>{this.prune(d);const user=d.operatorUsers.find(u=>u.email===email&&u.status==='ACTIVE');if(!user)return;for(const link of d.operatorLinks.filter(l=>l.userId===user.id))link.usedAt=this.now();const link={id:id(),userId:user.id,hash:digest(token),createdAt:this.now(),expiresAt:this.now()+ADMIN_LINK_MS,delivery:'PENDING' as const};d.operatorLinks.push(link);audit(d,'operator_login_requested',this.now(),{actor:user.id,code:user.id});return {user,link};});if(!delivery)return;
    try{const reference=await this.email.send(delivery.link.id,{to:delivery.user.email,subject:'Your Regstead operator sign-in link',text:`You requested access to the private Regstead operator console.\n\n${this.origin}/admin/auth/verify?token=${token}\n\nThis link expires in 15 minutes and can be used once. If you did not request access, ignore this email.`});await this.repository.transaction(d=>{const link=d.operatorLinks.find(l=>l.id===delivery.link.id);if(link){link.delivery='ACCEPTED';link.providerReference=reference;}});}catch{await this.repository.transaction(d=>{const link=d.operatorLinks.find(l=>l.id===delivery.link.id);if(link){link.delivery='FAILED';link.usedAt=this.now();}audit(d,'operator_login_delivery_failed',this.now(),{actor:delivery.user.id,code:delivery.user.id});});}
  }
  async verify(token:string,client:string,oldSession=''){await this.limit('verify:'+client,20);if(!/^[\w-]{43}$/.test(token))throw new Error('Invalid or expired link');const session=secret(),csrf=secret();await this.repository.transaction(d=>{this.prune(d);const link=d.operatorLinks.find(l=>l.hash===digest(token)&&!l.usedAt&&l.expiresAt>this.now()&&l.delivery==='ACCEPTED');const user=link&&d.operatorUsers.find(u=>u.id===link.userId&&u.status==='ACTIVE');if(!link||!user)throw new Error('Invalid or expired link');link.usedAt=this.now();d.operatorSessions=d.operatorSessions.filter(s=>s.hash!==digest(oldSession));d.operatorSessions.push({id:id(),userId:user.id,hash:digest(session),csrfHash:digest(csrf),createdAt:this.now(),expiresAt:this.now()+ADMIN_SESSION_MS});audit(d,'operator_login_succeeded',this.now(),{actor:user.id,code:user.id});});return {session,csrf};}
  async authenticate(token:string){if(!/^[\w-]{43}$/.test(token))throw new Error('Operator sign in required');const data=await this.repository.read();const session=data.operatorSessions.find(s=>s.hash===digest(token)&&s.expiresAt>this.now());const user=session&&data.operatorUsers.find(u=>u.id===session.userId&&u.status==='ACTIVE');if(!session||!user)throw new Error('Operator sign in required');return {data,user,session};}
  async csrf(token:string,csrf:string){const context=await this.authenticate(token);if(!csrf||!equal(context.session.csrfHash,digest(csrf)))throw new Error('Invalid request');return context;}
  async logout(token:string,csrf:string){const {user}=await this.csrf(token,csrf);await this.repository.transaction(d=>{d.operatorSessions=d.operatorSessions.filter(s=>s.hash!==digest(token));audit(d,'operator_logout',this.now(),{actor:user.id,code:user.id});});}
}
