import {cp,mkdir,readdir,readFile,writeFile,stat} from 'node:fs/promises';
import {resolve,relative,join,isAbsolute} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {digest} from './operations.js';
import {SqliteCommercialRepository} from './repository.js';
interface BackupManifest {version:1;engineRoot:string;files:{path:string;hash:string}[];createdAt:string}
async function files(root:string,sub=''):Promise<string[]>{const found:string[]=[];for(const entry of await readdir(join(root,sub),{withFileTypes:true})){const name=join(sub,entry.name);if(entry.isSymbolicLink())throw new Error('Backup refuses symlinks');if(entry.isDirectory())found.push(...await files(root,name));else if(entry.isFile())found.push(name);}return found;}
async function newDirectory(path:string){try{await stat(path);throw new Error('Destination already exists');}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}await mkdir(path,{recursive:true,mode:0o700});}
function inside(root:string,path:string){const r=relative(resolve(root),resolve(path));if(r.startsWith('..')||isAbsolute(r))throw new Error('Path outside backup scope');return r;}
/** Stop HTTP and worker first. Engine databases must be quiescent; no automatic process termination. */
export async function backupPilot(input:{database:string;engineRoot:string;reportRoot:string;destination:string;servicesStopped:boolean}){if(!input.servicesStopped)throw new Error('Stop services before backup');if(!(await stat(input.database)).isFile())throw new Error('Missing commercial database');const dest=resolve(input.destination);for(const root of [input.engineRoot,input.reportRoot]){const r=relative(resolve(root),dest);if(!r.startsWith('..')&&!isAbsolute(r))throw new Error('Backup destination must be outside source storage');}await newDirectory(dest);const db=new DatabaseSync(input.database);try{db.exec("VACUUM INTO '"+join(dest,'commercial.db').replaceAll("'","''")+"'");}finally{db.close();}for(const [source,target] of [[input.engineRoot,'engine'],[input.reportRoot,'reports']]){for(const file of await files(source)){if(file.endsWith('worker.lock'))throw new Error('Engine lock present: inspect stopped worker before backup');if(/\.(?:env|key|pem|pfx)$/i.test(file))throw new Error('Unexpected secret-like file in storage');}await cp(source,join(dest,target),{recursive:true,errorOnExist:true,force:false});}const manifest:BackupManifest={version:1,engineRoot:resolve(input.engineRoot),createdAt:new Date().toISOString(),files:[]};for(const path of await files(dest))manifest.files.push({path,hash:digest(await readFile(join(dest,path)))});await writeFile(join(dest,'manifest.json'),JSON.stringify(manifest,null,2),{flag:'wx',mode:0o600});return {destination:dest,files:manifest.files.length};}
export async function restorePilot(source:string,destination:string){source=resolve(source);destination=resolve(destination);const manifest=JSON.parse(await readFile(join(source,'manifest.json'),'utf8')) as BackupManifest;if(manifest.version!==1)throw new Error('Unsupported backup');for(const f of manifest.files){inside(source,join(source,f.path));if(digest(await readFile(join(source,f.path)))!==f.hash)throw new Error('Backup hash mismatch');}await newDirectory(destination);for(const f of manifest.files){const dest=join(destination,f.path);inside(destination,dest);await mkdir(resolve(dest,'..'),{recursive:true});await cp(join(source,f.path),dest,{errorOnExist:true,force:false});}const repo=new SqliteCommercialRepository(join(destination,'commercial.db'));try{await repo.transaction(d=>{d.portalSessions=[];d.portalLinks=[];d.operatorSessions=[];d.operatorLinks=[];d.portalForms=[];d.portalRates=[];for(const run of d.runs)run.reference=join(destination,'engine',inside(manifest.engineRoot,run.reference));});const data=await repo.read();for(const report of data.reports.filter(r=>r.status==='RELEASED')){if(!report.artifact||!/^[a-zA-Z0-9_-]+\.html$/.test(report.artifact)||digest(await readFile(join(destination,'reports',report.artifact)))!==report.hash)throw new Error('Restored report hash mismatch');}return {organisations:data.organisations.length,reports:data.reports.filter(r=>r.status==='RELEASED').length,runs:data.runs.length,sessionsRevoked:true};}finally{await repo.close();}}
