import Stripe from 'stripe';
import {randomBytes} from 'node:crypto';
import type {Checkout,Repository,Subscription,Versions,Webhook} from './types.js';
import {OperationalError} from './types.js';
import {audit,enqueue,id,notify,required} from './operations.js';
export interface BillingConfig {productId:string;monitorPriceId:string;portalConfigId?:string;baseUrl:string;termsVersion:string;graceMs:number;liveMode:boolean}
export interface SubscriptionTruth {id:string;customerId:string;priceId:string;productId:string;status:string;periodEnd:number;cancelAtPeriodEnd:boolean;metadata:Record<string,string>;quantity:number;currency:string;amount:number;interval:string}
export interface BillingProvider {checkout(checkout:Checkout,email:string):Promise<{id:string;url:string}>;billingPortal(customerId:string):Promise<string>;subscription(id:string):Promise<SubscriptionTruth>;verify(body:Buffer,signature:string):Webhook}
export class StripeProvider implements BillingProvider {
  private stripe:Stripe;
  constructor(key:string,private secret:string,private config:BillingConfig,client?:Stripe){this.stripe=client??new Stripe(key,{apiVersion:'2026-08-26.dahlia',maxNetworkRetries:2,timeout:15000});}
  async checkout(checkout:Checkout,email:string){const price=await this.stripe.prices.retrieve(checkout.priceId);const product=typeof price.product==='string'?price.product:price.product.id;if(product!==this.config.productId||price.id!==this.config.monitorPriceId||!price.active||price.currency!=='gbp'||price.unit_amount!==1699||price.recurring?.interval!=='month'||price.recurring.interval_count!==1)throw new OperationalError('INVALID_CONFIGURATION');const metadata={product:'regstead',organisationId:checkout.organisationId,checkoutId:checkout.id};const session=await this.stripe.checkout.sessions.create({mode:'subscription',client_reference_id:checkout.id,customer_email:email,line_items:[{price:checkout.priceId,quantity:1}],metadata,subscription_data:{metadata},success_url:`${this.config.baseUrl}/scan?checkout=complete`,cancel_url:`${this.config.baseUrl}/scan`,integration_identifier:`regstead_${[...randomBytes(8)].map(b=>String.fromCharCode(97+b%26)).join('')}`},{idempotencyKey:`regstead-checkout-${checkout.id}`});if(!session.url)throw new OperationalError('STRIPE_WEBHOOK_FAILURE');return {id:session.id,url:session.url};}
  async billingPortal(customerId:string){return (await this.stripe.billingPortal.sessions.create({customer:customerId,return_url:this.config.baseUrl,...(this.config.portalConfigId?{configuration:this.config.portalConfigId}:{})})).url;}
  async subscription(id:string){const s=await this.stripe.subscriptions.retrieve(id,{expand:['items.data.price.product']});if(s.items.data.length!==1)throw new Error('Regstead requires one subscription item');const item=s.items.data[0],p=item.price;return {id:s.id,customerId:typeof s.customer==='string'?s.customer:s.customer.id,priceId:p.id,productId:typeof p.product==='string'?p.product:p.product.id,status:s.status,periodEnd:item.current_period_end*1000,cancelAtPeriodEnd:s.cancel_at_period_end,metadata:s.metadata,quantity:item.quantity??0,currency:p.currency,amount:p.unit_amount??0,interval:p.recurring?.interval??''};}
  verify(body:Buffer,signature:string):Webhook {
    const e=this.stripe.webhooks.constructEvent(body,signature,this.secret,300);if(e.livemode!==this.config.liveMode)throw new Error('Wrong Stripe mode');
    const object=e.data.object as unknown as Record<string,unknown>;const stringId=(value:unknown):string|undefined=>typeof value==='string'?value:value&&typeof value==='object'&&'id' in value?String(value.id):undefined;
    const parent=object.parent as {subscription_details?:{subscription?:unknown}}|undefined;
    const sub=e.type.startsWith('customer.subscription.')?stringId(object.id):stringId(object.subscription??parent?.subscription_details?.subscription);
    return {id:e.id,type:e.type,created:e.created,subscriptionId:sub,checkoutId:e.type.startsWith('checkout.session.')?stringId(object.client_reference_id):undefined,status:'QUEUED',attempts:0};
  }
}
const EVENTS=new Set(['checkout.session.completed','checkout.session.async_payment_succeeded','invoice.paid','invoice.payment_failed','customer.subscription.updated','customer.subscription.deleted']);
export class Billing {
  constructor(private repository:Repository,private provider:BillingProvider,private config:BillingConfig,private versions:Versions,private now=Date.now){}
  async checkout(organisationId:string,termsVersion:string,actor:string){required(actor);if(termsVersion!==this.config.termsVersion)throw new Error('Current terms must be accepted');const checkout=await this.repository.transaction(d=>{const org=d.organisations.find(o=>o.id===organisationId);if(!org)throw new Error('Unknown organisation');if(d.subscriptions.some(s=>s.organisationId===organisationId&&!['canceled','incomplete_expired'].includes(s.status)))throw new Error('Subscription already exists');const previous=d.checkouts.find(c=>c.organisationId===organisationId&&!c.subscriptionId);if(previous){if(previous.priceId!==this.config.monitorPriceId||previous.termsVersion!==termsVersion)throw new Error('Pending checkout uses different terms or price; resolve it before continuing');return previous;}
      const c:Checkout={id:id(),organisationId,priceId:this.config.monitorPriceId,termsVersion,acceptedAt:this.now(),createdAt:this.now()};d.checkouts.push(c);audit(d,'terms_accepted',this.now(),{organisationId,actor});return c;});
    if(checkout.url)return checkout;const org=(await this.repository.read()).organisations.find(o=>o.id===organisationId)!;const session=await this.provider.checkout(checkout,org.contactEmail);return this.repository.transaction(d=>{const c=d.checkouts.find(c=>c.id===checkout.id)!;if(c.sessionId&&c.sessionId!==session.id)throw new Error('Checkout idempotency conflict');c.sessionId=session.id;c.url=session.url;return c;});
  }
  async billingPortal(organisationId:string){const sub=(await this.repository.read()).subscriptions.filter(s=>s.organisationId===organisationId).at(-1);if(!sub)throw new Error('No linked subscription');return this.provider.billingPortal(sub.stripeCustomerId);}
  async receive(body:Buffer,signature:string){if(body.length>262144)throw new Error('Webhook too large');const event=this.provider.verify(body,signature);return this.repository.transaction(d=>{const previous=d.webhooks.find(e=>e.id===event.id);if(previous)return previous;event.status=EVENTS.has(event.type)?'QUEUED':'IGNORED';d.webhooks.push(event);audit(d,'webhook_received',this.now());return event;});}
  async processOne(){const event=await this.repository.transaction(d=>{const now=this.now();for(const e of d.webhooks)if(e.status==='PROCESSING'&&(e.leaseUntil??0)<now){e.status=e.attempts<3?'QUEUED':'FAILED';e.token=undefined;}if(d.webhooks.some(e=>e.status==='PROCESSING'))return undefined;const e=d.webhooks.find(e=>e.status==='QUEUED');if(!e)return undefined;e.status='PROCESSING';e.token=id();e.leaseUntil=now+120000;e.attempts++;return e;});if(!event)return false;
    try{if(!event.subscriptionId)throw new Error('Missing subscription graph');const truth=await this.provider.subscription(event.subscriptionId);await this.repository.transaction(d=>{
      const current=d.webhooks.find(e=>e.id===event.id)!;if(current.token!==event.token||current.status!=='PROCESSING'||(current.leaseUntil??0)<this.now())throw new Error('Webhook lease lost');
      const finish=(status:'PROCESSED'|'IGNORED')=>{current.status=status;current.token=undefined;current.leaseUntil=undefined;audit(d,'webhook_processed',this.now());};
      if(truth.productId!==this.config.productId||truth.priceId!==this.config.monitorPriceId||truth.metadata.product!=='regstead'){finish('IGNORED');return;}
      if(truth.quantity!==1||truth.currency!=='gbp'||truth.interval!=='month'||truth.amount!==1699)throw new Error('Unexpected Regstead price');
      const old=d.subscriptions.find(s=>s.stripeSubscriptionId===truth.id);const checkout=d.checkouts.find(c=>c.id===(old?truth.metadata.checkoutId:event.checkoutId??truth.metadata.checkoutId));
      if(!checkout||checkout.organisationId!==truth.metadata.organisationId||checkout.priceId!==truth.priceId||checkout.subscriptionId&&checkout.subscriptionId!==truth.id||old&&old.organisationId!==checkout.organisationId)throw new Error('Unbound subscription');
      if(old&&['canceled','incomplete_expired'].includes(old.status)&&d.subscriptions.some(s=>s.organisationId===old.organisationId&&s.id!==old.id&&!['canceled','incomplete_expired'].includes(s.status))){finish('IGNORED');return;}
      if(d.subscriptions.some(s=>s.organisationId===checkout.organisationId&&s.stripeSubscriptionId!==truth.id&&!['canceled','incomplete_expired'].includes(s.status)))throw new Error('Duplicate active subscription');
      const org=d.organisations.find(o=>o.id===checkout.organisationId)!;
      // Every event refreshes current Stripe truth; old invoice payloads never revive cancelled service.
      const status=old?.status==='canceled'?'canceled':truth.status;const now=this.now();const sub:Subscription={id:old?.id??id(),organisationId:org.id,provider:'stripe',stripeCustomerId:truth.customerId,stripeSubscriptionId:truth.id,stripePriceId:truth.priceId,status,currentPeriodEnd:truth.periodEnd,cancelAtPeriodEnd:truth.cancelAtPeriodEnd,createdAt:old?.createdAt??now,updatedAt:now,lastEventCreated:Math.max(old?.lastEventCreated??0,event.created),graceDeadline:status==='past_due'?old?.graceDeadline??now+this.config.graceMs:undefined};
      if(old)Object.assign(old,sub);else d.subscriptions.push(sub);checkout.subscriptionId=truth.id;org.status=['active','past_due'].includes(status)?'ACTIVE':'INACTIVE';org.updatedAt=now;
      const site=d.sites.find(s=>s.organisationId===org.id)!;site.active=['active','past_due'].includes(status);site.updatedAt=now;
      if(status==='active')enqueue(d,site,'BASELINE',`baseline:${site.id}`,now,this.versions);
      if(status==='past_due')notify(d,`payment:${truth.id}:${truth.periodEnd}`,org.id,'PAYMENT_FAILURE',now);
      if(status==='canceled'){for(const job of d.jobs)if(job.organisationId===org.id&&job.status==='QUEUED'&&job.type==='MONITORING'&&!job.manualAuthorisation)job.status='CANCELLED';notify(d,`cancel:${truth.id}`,org.id,'CANCELLATION',now);}
      finish('PROCESSED');
    });}catch{await this.repository.transaction(d=>{const e=d.webhooks.find(e=>e.id===event.id)!;if(e.token!==event.token)return;e.status='FAILED';e.failureCode='STRIPE_WEBHOOK_FAILURE';e.token=undefined;e.leaseUntil=undefined;audit(d,'webhook_failed',this.now(),{code:'STRIPE_WEBHOOK_FAILURE'});});}return true;
  }
  async retry(eventId:string,actor:string){required(actor);await this.repository.transaction(d=>{const e=d.webhooks.find(e=>e.id===eventId);if(!e||e.status!=='FAILED')throw new Error('Not a failed webhook');e.status='QUEUED';audit(d,'webhook_retry',this.now(),{actor});});}
}
