import type {EmailProvider,Repository} from './types.js';
import {digest} from './operations.js';
/** Provider acceptance is not evidence of inbox delivery. Never retry beyond its 24-hour deduplication window. */
export class ResendEmailProvider implements EmailProvider {
  constructor(private repository:Repository,private key:string,private from:string,private fetcher:typeof fetch=fetch,private now=Date.now,private replyTo?:string){}
  async send(key:string,message:{to:string;subject:string;text:string}){const address='[^\\s<>@]+@[^\\s<>@]+\\.[^\\s<>@]+';if(!new RegExp(`^(?:[^<>\\r\\n]+ <${address}>|${address})$`).test(this.from)||this.replyTo&&!new RegExp(`^${address}$`).test(this.replyTo))throw new Error('Invalid sender');const body=JSON.stringify({from:this.from,to:[message.to],subject:message.subject,text:message.text,...(this.replyTo?{reply_to:this.replyTo}:{})}),hash=digest(body);const previous=await this.repository.transaction(d=>{let record=d.emailDeliveries.find(r=>r.id===key);if(record){if(record.hash!==hash)throw new Error('Email identity conflict');if(record.reference)return record.reference;if(this.now()-record.startedAt>23*3600_000)throw new Error('Provider reconciliation required');if((record.leaseUntil??0)>this.now())throw new Error('Delivery already in progress');}else{record={id:key,hash,startedAt:this.now(),status:'PENDING'};d.emailDeliveries.push(record);}record.leaseUntil=this.now()+60_000;return undefined;});if(previous)return previous;
    try{const response=await this.fetcher('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${this.key}`,'Content-Type':'application/json','Idempotency-Key':key},body,signal:AbortSignal.timeout(15_000),redirect:'error'});if(!response.ok)throw new Error('Provider rejected email');const result=await response.json() as {id?:unknown};if(typeof result.id!=='string'||!result.id)throw new Error('Missing acknowledgement');const reference='resend:'+result.id;await this.repository.transaction(d=>{const r=d.emailDeliveries.find(r=>r.id===key)!;r.reference=reference;r.status='ACCEPTED';r.leaseUntil=undefined;});return reference;
    }catch{await this.repository.transaction(d=>{const r=d.emailDeliveries.find(r=>r.id===key)!;r.status='FAILED';r.leaseUntil=undefined;});throw new Error('Email delivery unavailable');}
  }
}
/** Authentication links must never be written to the ordinary development spool. */
export class UnavailableAuthEmail implements EmailProvider {async send():Promise<string>{throw new Error('Authentication email provider not configured');}}
