import {createHash,randomUUID,timingSafeEqual} from 'node:crypto';
import type {Audit,Data,Job,JobType,Repository,Site,Template,Versions} from './types.js';
import {OperationalError} from './types.js';
import {normalize,resolvePublic} from '../utils/urls.js';
import {APPLICATION_VERSION} from '../snapshots/types.js';
import {BROWSER_POLICY_VERSION} from '../browser/types.js';
import {lawPack} from '../lawwatch/pack.js';
export const id=()=>randomUUID();
export const digest=(value:string|Buffer)=>createHash('sha256').update(value).digest('hex');
export const versions=(release:string):Versions=>({engineVersion:APPLICATION_VERSION,packVersion:lawPack.version,browserPolicyVersion:BROWSER_POLICY_VERSION,release});
export function required(value:string,max=500):string {if(typeof value!=='string'||!value.trim()||value.length>max)throw new OperationalError('INVALID_CONFIGURATION');return value.trim();}
export function authenticate(token:string|undefined,expected:string,actor:string){if(expected.length<32||!token||!timingSafeEqual(Buffer.from(digest(token)),Buffer.from(digest(expected))))throw new Error('Unauthorized');return required(actor,100);}
export function audit(data:Data,event:string,now:number,ids:Omit<Audit,'id'|'event'|'at'>={}){data.audit.push({id:id(),event,at:now,...ids});}
export function notify(data:Data,key:string,organisationId:string,template:Template,now:number,reportId?:string){if(data.notifications.some(n=>n.key===key))return;data.notifications.push({id:id(),key,organisationId,template,reportId,status:'QUEUED',attempts:0});audit(data,'email_queued',now,{organisationId,reportId});}
export function entitled(data:Data,organisationId:string,now:number){return data.organisations.some(o=>o.id===organisationId&&o.status==='ACTIVE')&&data.subscriptions.some(s=>s.organisationId===organisationId&&((s.status==='active'&&s.currentPeriodEnd>now)||(s.status==='past_due'&&(s.graceUntil??0)>now)));}
export function enqueue(data:Data,site:Site,type:JobType,key:string,now:number,v:Versions,manualAuthorisation?:string):Job{
  const duplicate=data.jobs.find(j=>j.key===key);if(duplicate)return duplicate;
  const open=data.jobs.find(j=>j.siteId===site.id&&['QUEUED','RUNNING','AWAITING_REVIEW','APPROVED'].includes(j.status));if(open)return open;
  const job:Job={id:id(),key,organisationId:site.organisationId,siteId:site.id,type,status:'QUEUED',scheduledAt:now,retryCount:0,...v,manualAuthorisation};data.jobs.push(job);audit(data,'job_queued',now,{organisationId:site.organisationId,siteId:site.id,jobId:job.id});return job;
}
export class Operations {
  constructor(public repository:Repository,public version:Versions,private now=Date.now,private checkUrl:typeof resolvePublic=resolvePublic){}
  async onboard(input:{legalName:string;displayName?:string;contactName:string;contactEmail:string;url:string;notes?:string;cadenceMs:number;browserFallback?:boolean},actor:string){required(actor,100);if(input.browserFallback!==undefined&&typeof input.browserFallback!=='boolean')throw new OperationalError('INVALID_CONFIGURATION');const url=normalize(input.url);await this.checkUrl(new URL(url).hostname);const email=required(input.contactEmail,254);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!Number.isSafeInteger(input.cadenceMs)||input.cadenceMs<3600000)throw new OperationalError('INVALID_CONFIGURATION');return this.repository.transaction(d=>{if(d.sites.some(s=>s.hostname===new URL(url).hostname))throw new Error('Site already registered');const now=this.now(),org={id:id(),legalName:required(input.legalName),displayName:required(input.displayName??input.legalName),contactName:required(input.contactName),contactEmail:email,notes:input.notes?required(input.notes,2000):'',status:'LEAD' as const,createdAt:now,updatedAt:now,foundingCustomer:false};const site:Site={id:id(),organisationId:org.id,canonicalUrl:url,hostname:new URL(url).hostname,active:true,paused:false,pack:'lawwatch-england-wales',browserFallback:input.browserFallback??false,createdAt:now,updatedAt:now,nextRunAt:now+input.cadenceMs,cadenceMs:input.cadenceMs};d.organisations.push(org);d.sites.push(site);const job=enqueue(d,site,'BASELINE',`baseline:${site.id}`,now,this.version,actor);audit(d,'organisation_created',now,{organisationId:org.id,siteId:site.id,actor});notify(d,`onboarding:${org.id}`,org.id,'ONBOARDING',now);return {organisation:org,site,job};});}
  async queue(siteId:string,type:JobType,requestKey:string,actor:string){required(actor);required(requestKey,100);return this.repository.transaction(d=>{const site=d.sites.find(s=>s.id===siteId);if(!site)throw new Error('Unknown site');return enqueue(d,site,type,type==='BASELINE'?`baseline:${site.id}`:`manual:${site.id}:${requestKey}`,this.now(),this.version,actor);});}
  async schedule(){return this.repository.transaction(d=>{const now=this.now();let count=0;for(const site of d.sites){if(!site.active||site.paused||site.nextRunAt>now||!entitled(d,site.organisationId,now)||d.jobs.some(j=>j.siteId===site.id&&['QUEUED','RUNNING','AWAITING_REVIEW','APPROVED'].includes(j.status)))continue;enqueue(d,site,'MONITORING',`monitor:${site.id}:${site.nextRunAt}`,now,this.version);site.nextRunAt=now+site.cadenceMs;count++;}return count;});}
  async pause(siteId:string,paused:boolean,actor:string){required(actor);await this.repository.transaction(d=>{const site=d.sites.find(s=>s.id===siteId);if(!site)throw new Error('Unknown site');site.paused=paused;site.updatedAt=this.now();audit(d,paused?'monitoring_paused':'monitoring_resumed',this.now(),{siteId,organisationId:site.organisationId,actor});});}
  async retry(jobId:string,actor:string){required(actor);await this.repository.transaction(d=>{const job=d.jobs.find(j=>j.id===jobId);if(!job||job.status!=='FAILED')throw new Error('Only failed jobs can be retried');job.status='QUEUED';job.scheduledAt=this.now();job.failureCode=undefined;job.token=undefined;job.leaseUntil=undefined;audit(d,'job_retry_requested',this.now(),{jobId,actor});});}
  async review(reportId:string,findingId:string,status:'APPROVED'|'SUPPRESSED'|'ANNOTATED',note:string,actor:string,title?:string,explanation?:string){required(actor,100);required(note,2000);if(!['APPROVED','SUPPRESSED','ANNOTATED'].includes(status))throw new Error('Invalid review');for(const text of [title,explanation,note])if(text&&/\b(non[- ]?compliant|breach(?:es)?|illegal|legally compliant|certif(?:y|ies) compliance)\b/i.test(text))throw new Error('Unsupported legal conclusion');return this.repository.transaction(d=>{const report=d.reports.find(r=>r.id===reportId);if(!report||report.status!=='DRAFT'||!report.findings.some(f=>f.id===findingId))throw new Error('Review requires draft finding');if(title)required(title,500);if(explanation)required(explanation,4000);d.reviews.push({id:id(),reportId,findingId,status,reviewer:actor,reviewedAt:this.now(),note,title,explanation});const done=report.findings.every(f=>d.reviews.some(r=>r.reportId===reportId&&r.findingId===f.id));d.jobs.find(j=>j.id===report.jobId)!.status=done?'APPROVED':'AWAITING_REVIEW';audit(d,'finding_reviewed',this.now(),{reportId,jobId:report.jobId,organisationId:report.organisationId,actor});});}
}
