import {readFile} from 'node:fs/promises';
import type {IncomingMessage,ServerResponse} from 'node:http';
import type {ArtifactStore,Data,Report} from './types.js';
import type {Billing} from './billing.js';
import {PortalAccess,SESSION_MS} from './portal-access.js';
import {audit,digest,entitled} from './operations.js';
import {labels} from './reports.js';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const style=`@font-face{font-family:Inter;font-style:normal;font-weight:400;font-display:swap;src:url('/portal/assets/inter-400.ttf')}@font-face{font-family:Inter;font-style:normal;font-weight:600;font-display:swap;src:url('/portal/assets/inter-600.ttf')}@font-face{font-family:Manrope;font-style:normal;font-weight:600;font-display:swap;src:url('/portal/assets/manrope-600.ttf')}@font-face{font-family:Manrope;font-style:normal;font-weight:700;font-display:swap;src:url('/portal/assets/manrope-700.ttf')}:root{color-scheme:light}*{box-sizing:border-box}body{margin:0;background:#EFF4F5;color:#566675;font:16px/1.6 Inter,Arial,sans-serif;overflow-wrap:anywhere}header{background:#10263D;color:white;padding:20px}header a{color:white;margin-right:20px}main{max-width:1000px;margin:32px auto;padding:0 20px}h1,h2,h3{font-family:Manrope,Arial,sans-serif;color:#10263D;line-height:1.25}h1{font-size:2rem}.card{background:#F7F9FA;border:1px solid #d2dfe2;border-radius:12px;padding:24px;margin:20px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,220px),1fr));gap:16px}a{color:#116b60}button{background:#168678;color:white;border:0;border-radius:6px;padding:12px 18px;font:inherit;cursor:pointer}button:hover{background:#116b60}input{display:block;width:100%;max-width:420px;padding:12px;border:1px solid #566675;border-radius:6px;font:inherit}label{display:block;font-weight:bold}a:focus-visible,button:focus-visible,input:focus-visible{outline:3px solid #10263D;outline-offset:4px}dt{font-weight:bold;color:#10263D}dd{margin:0 0 12px}nav{display:flex;flex-wrap:wrap;gap:12px}.actions{display:flex;flex-wrap:wrap;gap:16px;align-items:center}footer{padding:24px;font-size:.9rem}section{min-width:0}@media(max-width:480px){main{margin:20px auto;padding:0 12px}.card{padding:18px}h1{font-size:1.7rem}}`;
const shell=(title:string,content:string,csrf?:string)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} | Regstead</title><style>${style}</style></head><body><header><nav aria-label="Main"><a href="/portal">Regstead</a>${csrf?'<a href="/portal/reports">Report history</a><a href="/portal/account">Your details</a>':''}</nav></header><main><h1>${esc(title)}</h1>${content}${csrf?`<form method="post" action="/portal/logout"><input type="hidden" name="csrf" value="${esc(csrf)}"><button type="submit">Sign out</button></form>`:''}</main><footer>Regstead, operated by Foundry Vale Ltd. Public website signals only; no regulatory certification.</footer></body></html>`;
const date=(n?:number)=>n?new Date(n).toISOString().replace('T',' ').replace('.000Z',' UTC'):'Not available';
const cookie=(name:string,value:string,maxAge:number)=>`${name}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`;
function cookies(req:IncomingMessage){const result:Record<string,string>={};for(const part of (req.headers.cookie??'').split(';')){const [key,...value]=part.trim().split('=');if(key)result[key]=value.join('=');}return result;}
function visible(data:Data,org:string){return data.reports.filter(r=>r.organisationId===org&&r.status==='RELEASED'&&r.customerVersion===1&&r.artifact&&r.hash&&r.customerSummary&&r.releasedAt).sort((a,b)=>b.releasedAt!-a.releasedAt!);}
function reportCards(data:Data,reports:Report[]){return reports.length?reports.map(r=>{const job=data.jobs.find(j=>j.id===r.jobId),type=job?.type==='BASELINE'?'Baseline':job?.type==='MONITORING'?'Monitoring':'Manual recheck';return `<article class="card"><h2>${type} report</h2><p>Report date: ${esc(date(r.createdAt))}<br>Released: ${esc(date(r.releasedAt))}</p><p>${Object.entries(labels).map(([key,label])=>`${esc(label)}: ${r.customerSummary![key]??0}`).join(' · ')}</p><div class="actions"><a href="/portal/reports/${esc(r.id)}">View ${type.toLowerCase()} report</a><a href="/portal/reports/${esc(r.id)}/download">Download HTML report</a></div></article>`;}).join(''):'<p>No customer-ready reports have been released yet.</p>';}
export class CustomerPortal {
  constructor(readonly access:PortalAccess,private storage:ArtifactStore,private billing:Billing|undefined,private trustedProxyAddress?:string,private now=Date.now){}
  private headers(res:ServerResponse){res.setHeader('Cache-Control','no-store, private');res.setHeader('Referrer-Policy','strict-origin');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Strict-Transport-Security','max-age=31536000');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Content-Security-Policy',`default-src 'none'; font-src 'self'; style-src 'sha256-${Buffer.from(digest(style),'hex').toString('base64')}'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'`);}
  private html(res:ServerResponse,body:string,status=200){res.statusCode=status;res.setHeader('Content-Type','text/html; charset=utf-8');res.end(body);}
  private redirect(res:ServerResponse,to:string){if(!to.startsWith('/portal')&&!/^https:\/\/billing\.stripe\.com\//.test(to))throw new Error('Invalid redirect');res.statusCode=303;res.setHeader('Location',to);res.end();}
  private async form(req:IncomingMessage){if(!req.headers['content-type']?.startsWith('application/x-www-form-urlencoded'))throw new Error('Invalid request');const chunks:Buffer[]=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>4096)throw new Error('Invalid request');chunks.push(Buffer.from(chunk));}return new URLSearchParams(Buffer.concat(chunks).toString());}
  async handle(req:IncomingMessage,res:ServerResponse):Promise<boolean>{if(!req.url?.startsWith('/portal'))return false;this.headers(res);try{const origin=new URL(this.access.origin);if(req.headers.host!==origin.host)throw new Error('Invalid host');const directTLS=!!(req.socket as {encrypted?:boolean}).encrypted;const proxyTLS=this.trustedProxyAddress&&req.socket.remoteAddress===this.trustedProxyAddress&&req.headers['x-forwarded-proto']==='https';if(!directTLS&&!proxyTLS)throw new Error('HTTPS required');if(req.method==='POST'&&req.headers.origin!==this.access.origin)throw new Error('Invalid origin');const url=new URL(req.url,this.access.origin),path=url.pathname,c=cookies(req),client=req.socket.remoteAddress??'unknown';
      if(req.method==='GET'&&/^\/portal\/assets\/(inter-(400|600)|manrope-(600|700))\.ttf$/.test(path)){const name=path.split('/').at(-1)!;res.setHeader('Content-Type','font/ttf');res.end(await readFile(new URL('../../assets/portal/'+name,import.meta.url)));return true;}
      if(req.method==='GET'&&(path==='/portal/login'||path==='/portal/auth/verify')){await this.access.limit('form:'+client,60);const csrf=await this.access.form();res.setHeader('Set-Cookie',cookie('__Host-regstead-form',csrf,900));const verify=path.endsWith('/verify');const fields=verify?`<p>Confirm that you requested this sign-in link.</p><input type="hidden" name="token" value="${esc(url.searchParams.get('token')??'')}">`:'<label for="email">Email address</label><input id="email" name="email" type="email" autocomplete="email" required maxlength="254" aria-describedby="login-help"><p id="login-help">Use your authorised organisation contact address.</p>';this.html(res,shell(verify?'Confirm sign-in':'Customer sign-in',`<section class="card"><form method="post" action="${verify?'/portal/auth/verify':'/portal/login'}"><input type="hidden" name="csrf" value="${csrf}">${fields}<button type="submit">${verify?'Sign in':'Email me a sign-in link'}</button></form></section>`));return true;}
      if(req.method==='POST'&&(path==='/portal/login'||path==='/portal/auth/verify')){const form=await this.form(req);await this.access.consumeForm(form.get('csrf')??'',c['__Host-regstead-form']??'');if(path==='/portal/login'){try{await this.access.request(form.get('email')??'',client);}catch{}this.html(res,shell('Check your email','<p>If this address is authorised and requests are within the limit, a sign-in link will arrive shortly. The link expires in 15 minutes.</p>'));return true;}const session=await this.access.verify(form.get('token')??'',client,c['__Host-regstead-session']);res.setHeader('Set-Cookie',[cookie('__Host-regstead-session',session.session,SESSION_MS/1000),cookie('__Host-regstead-csrf',session.csrf,SESSION_MS/1000),cookie('__Host-regstead-form','',0)]);this.redirect(res,'/portal');return true;}
      let context;try{context=await this.access.authenticate(c['__Host-regstead-session']??'');}catch{this.redirect(res,'/portal/login');return true;}const {data,user}=context,csrf=c['__Host-regstead-csrf']??'',session=c['__Host-regstead-session'];
      if(req.method==='POST'){const form=await this.form(req);await this.access.csrf(session,form.get('csrf')??'');if(path==='/portal/logout'){await this.access.logout(session,form.get('csrf')??'');res.setHeader('Set-Cookie',[cookie('__Host-regstead-session','',0),cookie('__Host-regstead-csrf','',0)]);this.redirect(res,'/portal/login');return true;}if(path==='/portal/billing/manage'){await this.access.limit('billing:'+user.id,5);if(!this.billing)throw new Error('Billing unavailable');const to=await this.billing.billingPortal(user.organisationId);if(new URL(to).origin!=='https://billing.stripe.com')throw new Error('Invalid redirect');await this.access.repository.transaction(d=>audit(d,'billing_portal_opened',this.now(),{organisationId:user.organisationId,code:user.id}));this.redirect(res,to);return true;}}
      if(req.method!=='GET'){this.html(res,shell('Not found','<p>This page is unavailable.</p>'),404);return true;}
      const reports=visible(data,user.organisationId),org=data.organisations.find(o=>o.id===user.organisationId)!,site=data.sites.find(s=>s.organisationId===user.organisationId),sub=data.subscriptions.filter(s=>s.organisationId===user.organisationId).at(-1);
      if(path==='/portal'){const stale=sub&&this.now()-sub.updatedAt>24*3600_000;const status=stale?'Status needs confirmation':!sub?'Approved pilot':sub.status==='canceled'?'Cancelled':sub.status==='past_due'?'Payment issue':sub.cancelAtPeriodEnd?'Cancels at period end':sub.status==='active'?'Active':'Not active';const monitoring=site?.paused?'Paused':stale?'Needs confirmation':site?.active&&entitled(data,user.organisationId,this.now())?'Active':'Not scheduled';this.html(res,shell('Regstead Monitor',`<section class="card"><h2>${esc(org.displayName)}</h2><p>${esc(site?.hostname)}</p><p>£16.99/month · One primary website</p><dl><dt>Subscription</dt><dd>${esc(status)}</dd><dt>Current period end</dt><dd>${esc(date(sub?.currentPeriodEnd))}</dd><dt>Last billing confirmation</dt><dd>${esc(date(sub?.updatedAt))}</dd></dl>${sub?`<form action="/portal/billing/manage" method="post"><input type="hidden" name="csrf" value="${esc(csrf)}"><button>Manage subscription in Stripe Billing Portal</button></form>`:''}</section><section class="card"><h2>Monitoring</h2><dl><dt>State</dt><dd>${monitoring}</dd><dt>Last successful scan</dt><dd>${esc(date(site?.lastSuccessfulRunAt))}</dd><dt>Next scheduled scan</dt><dd>${monitoring==='Active'?esc(date(site?.nextRunAt)):'Not scheduled / awaiting confirmation'}</dd><dt>Latest released report</dt><dd>${esc(date(reports[0]?.releasedAt))}</dd></dl><p>Scheduling remains subject to scan completion and human review.</p></section><h2>Latest released report</h2>${reportCards(data,reports.slice(0,1))}`,csrf));return true;}
      if(path==='/portal/reports'){this.html(res,shell('Report history',reportCards(data,reports),csrf));return true;}
      if(path==='/portal/account'){this.html(res,shell('Your details',`<section class="card"><dl><dt>Contact name</dt><dd>${esc(user.displayName)}</dd><dt>Contact email</dt><dd>${esc(user.email)}</dd><dt>Organisation</dt><dd>${esc(org.displayName)}</dd><dt>Monitored website</dt><dd>${esc(site?.hostname)}</dd></dl><p>Contact your operator to request changes.</p></section>`,csrf));return true;}
      const match=/^\/portal\/reports\/([a-zA-Z0-9-]+)(\/download)?$/.exec(path);if(match){const report=reports.find(r=>r.id===match[1]);if(report){const bytes=await this.storage.get(report.artifact!);if(digest(bytes)!==report.hash)throw new Error('Report integrity failure');await this.access.repository.transaction(d=>audit(d,match[2]?'report_downloaded':'report_viewed',this.now(),{organisationId:user.organisationId,reportId:report.id,code:user.id}));res.setHeader('Content-Security-Policy',"sandbox; default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'");res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Content-Disposition',`${match[2]?'attachment':'inline'}; filename="regstead-report-${report.id}.html"`);res.end(bytes);return true;}}
      this.html(res,shell('Not found','<p>This page is unavailable.</p>'),404);return true;
    }catch{this.html(res,shell('Request unavailable','<p>The request could not be completed. Your link may have expired. Return to <a href="/portal/login">customer sign-in</a> to try again.</p>'),400);return true;}}
}
