import {randomBytes,timingSafeEqual} from 'node:crypto';
import type {Data,EmailProvider,PortalUser,Repository} from './types.js';
import {audit,digest,entitled,id,required} from './operations.js';
export const LINK_MS=15*60_000,SESSION_MS=8*3600_000;
const secret=()=>randomBytes(32).toString('base64url');
const equal=(a:string,b:string)=>timingSafeEqual(Buffer.from(digest(a)),Buffer.from(digest(b)));
export class PortalAccess {
  constructor(readonly repository:Repository,private email:EmailProvider,readonly origin:string,private now=Date.now){const u=new URL(origin);if(u.protocol!=='https:'||u.origin!==origin)throw new Error('Portal requires an HTTPS origin');}
  async create(organisationId:string,email:string,displayName:string,actor:string,approvedPilot=false){required(actor);email=email.trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254)throw new Error('Invalid email');required(displayName,100);return this.repository.transaction(d=>{if(!d.organisations.some(o=>o.id===organisationId)||(!approvedPilot&&!entitled(d,organisationId,this.now())))throw new Error('Paid subscription or explicit pilot approval required');if(d.portalUsers.some(u=>u.email===email))throw new Error('Contact already authorised');const u:PortalUser={id:id(),organisationId,email,displayName,role:'OWNER',status:'ACTIVE',approvedPilot,createdAt:this.now(),updatedAt:this.now()};d.portalUsers.push(u);audit(d,'portal_user_created',this.now(),{organisationId,actor,code:u.id});return u;});}
  async disable(userId:string,actor:string){required(actor);await this.repository.transaction(d=>{const u=d.portalUsers.find(u=>u.id===userId);if(!u)throw new Error('Unknown contact');u.status='DISABLED';u.updatedAt=this.now();d.portalSessions=d.portalSessions.filter(s=>s.userId!==userId);for(const l of d.portalLinks.filter(l=>l.userId===userId))l.usedAt=this.now();audit(d,'portal_user_disabled',this.now(),{organisationId:u.organisationId,actor,code:u.id});});}
  private prune(d:Data){const now=this.now();d.portalRates=d.portalRates.filter(r=>r.expiresAt>now);d.portalForms=d.portalForms.filter(r=>r.expiresAt>now);d.portalSessions=d.portalSessions.filter(s=>s.expiresAt>now);d.portalLinks=d.portalLinks.filter(l=>l.expiresAt>now);}
  async limit(key:string,max:number,windowMs=15*60_000){const allowed=await this.repository.transaction(d=>{this.prune(d);const hash=digest(key);let r=d.portalRates.find(r=>r.id===hash);if(!r){if(d.portalRates.length>=10000)return false;r={id:hash,count:0,expiresAt:this.now()+windowMs};d.portalRates.push(r);}r.count++;return r.count<=max;});if(!allowed)throw new Error('Rate limited');}
  async form(){const token=secret();await this.repository.transaction(d=>{this.prune(d);if(d.portalForms.length>=10000)throw new Error('Rate limited');d.portalForms.push({id:digest(token),expiresAt:this.now()+LINK_MS});});return token;}
  async consumeForm(token:string,cookie:string){if(!token||!cookie||!equal(token,cookie))throw new Error('Invalid request');await this.repository.transaction(d=>{const i=d.portalForms.findIndex(f=>f.id===digest(token)&&f.expiresAt>this.now());if(i<0)throw new Error('Invalid request');d.portalForms.splice(i,1);});}
  async invite(userId:string,actor:string){required(actor);const user=(await this.repository.read()).portalUsers.find(u=>u.id===userId&&u.status==='ACTIVE');if(!user)throw new Error('Unavailable contact');await this.request(user.email,'operator:'+actor);}
  async request(email:string,client:string){await this.limit('login-ip:'+client,20);email=email.trim().toLowerCase();await this.limit('login-email:'+email,3);const token=secret();const delivery=await this.repository.transaction(d=>{this.prune(d);const user=d.portalUsers.find(u=>u.email===email&&u.status==='ACTIVE');if(!user)return;for(const link of d.portalLinks.filter(l=>l.userId===user.id))link.usedAt=this.now();const link={id:id(),userId:user.id,hash:digest(token),createdAt:this.now(),expiresAt:this.now()+LINK_MS,delivery:'PENDING' as const};d.portalLinks.push(link);audit(d,'portal_login_requested',this.now(),{organisationId:user.organisationId,code:user.id});return {user,link};});if(!delivery)return;
    // The raw link exists only in this call and the delivery provider; never in the database/spool/log.
    try{const reference=await this.email.send(delivery.link.id,{to:delivery.user.email,subject:'Your Regstead sign-in link',text:`You requested access to the Regstead Customer Portal.\n\n${this.origin}/portal/auth/verify?token=${token}\n\nThis link expires in 15 minutes and can be used once. If you did not request access, ignore this email.\nRegstead is operated by Foundry Vale Ltd.`});await this.repository.transaction(d=>{const l=d.portalLinks.find(l=>l.id===delivery.link.id);if(l){l.delivery='ACCEPTED';l.providerReference=reference;}});}catch{await this.repository.transaction(d=>{const l=d.portalLinks.find(l=>l.id===delivery.link.id);if(l){l.delivery='FAILED';l.usedAt=this.now();}audit(d,'portal_login_delivery_failed',this.now(),{organisationId:delivery.user.organisationId,code:delivery.user.id});});}
  }
  async verify(token:string,client:string,oldSession=''){await this.limit('verify:'+client,20);if(!/^[\w-]{43}$/.test(token))throw new Error('Invalid or expired link');const session=secret(),csrf=secret();await this.repository.transaction(d=>{this.prune(d);const link=d.portalLinks.find(l=>l.hash===digest(token)&&!l.usedAt&&l.expiresAt>this.now()&&l.delivery==='ACCEPTED');const user=link&&d.portalUsers.find(u=>u.id===link.userId&&u.status==='ACTIVE');if(!link||!user)throw new Error('Invalid or expired link');link.usedAt=this.now();d.portalSessions=d.portalSessions.filter(s=>s.hash!==digest(oldSession));d.portalSessions.push({id:id(),userId:user.id,hash:digest(session),csrfHash:digest(csrf),createdAt:this.now(),expiresAt:this.now()+SESSION_MS});audit(d,'portal_login_succeeded',this.now(),{organisationId:user.organisationId,code:user.id});});return {session,csrf};}
  async authenticate(token:string){if(!/^[\w-]{43}$/.test(token))throw new Error('Sign in required');const data=await this.repository.read();const session=data.portalSessions.find(s=>s.hash===digest(token)&&s.expiresAt>this.now());const user=session&&data.portalUsers.find(u=>u.id===session.userId&&u.status==='ACTIVE');if(!session||!user||!data.organisations.some(o=>o.id===user.organisationId))throw new Error('Sign in required');return {data,user,session};}
  async csrf(token:string,csrf:string){const context=await this.authenticate(token);if(!csrf||!equal(context.session.csrfHash,digest(csrf)))throw new Error('Invalid request');return context;}
  async logout(token:string,csrf:string){const {user}=await this.csrf(token,csrf);await this.repository.transaction(d=>{d.portalSessions=d.portalSessions.filter(s=>s.hash!==digest(token));audit(d,'portal_logout',this.now(),{organisationId:user.organisationId,code:user.id});});}
}
