import {DatabaseSync} from 'node:sqlite';
import {mkdirSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import {emptyData,type Data,type Repository} from './types.js';
export function migratePortalPayload(payload:string):string {const data=JSON.parse(payload);return JSON.stringify({...data,emailDeliveries:[],portalUsers:[],portalLinks:[],portalSessions:[],portalRates:[],portalForms:[]});}
export function migrateOperatorPayload(payload:string):string {const data=JSON.parse(payload);return JSON.stringify({...data,operatorUsers:[],operatorLinks:[],operatorSessions:[]});}
// The singleton is a small-cohort aggregate. Every writer takes the same short transaction lock.
export const MIGRATION_1=`CREATE TABLE regstead_state(id INTEGER PRIMARY KEY CHECK(id=1), schema_version INTEGER NOT NULL, model TEXT NOT NULL CHECK(model='monitor-v1'), payload TEXT NOT NULL);`;
export const POSTGRES_MIGRATION_1=MIGRATION_1;
export const DOWN_1='DROP TABLE regstead_state';
export function validate(data:Data):void {
  for(const records of [data.operatorUsers,data.operatorLinks,data.operatorSessions,data.emailDeliveries,data.portalUsers,data.portalLinks,data.portalSessions,data.portalRates,data.portalForms,data.organisations,data.sites,data.subscriptions,data.jobs,data.runs,data.reports,data.reviews,data.notifications,data.checkouts,data.webhooks,data.audit])if(new Set(records.map(r=>r.id)).size!==records.length)throw new Error('Duplicate record');
  for(const values of [data.jobs.map(x=>x.key),data.notifications.map(x=>x.key),data.subscriptions.map(x=>x.stripeSubscriptionId),data.runs.map(x=>x.jobId),data.reports.map(x=>x.jobId)])if(new Set<string|number>(values).size!==values.length)throw new Error('Duplicate invariant');
  for(const site of data.sites)if(!data.organisations.some(x=>x.id===site.organisationId))throw new Error('Missing organisation');
  for(const job of data.jobs)if(!data.sites.some(x=>x.id===job.siteId&&x.organisationId===job.organisationId))throw new Error('Missing site');
}
export class SqliteCommercialRepository implements Repository {
  private db:DatabaseSync;
  constructor(path:string){if(path!==':memory:')mkdirSync(dirname(resolve(path)),{recursive:true});this.db=new DatabaseSync(path);this.db.exec('PRAGMA journal_mode=WAL; PRAGMA busy_timeout=10000;');this.db.exec('BEGIN IMMEDIATE');try{if(!this.db.prepare("SELECT name FROM sqlite_master WHERE name='regstead_state'").get()){this.db.exec(MIGRATION_1);this.db.prepare("INSERT INTO regstead_state VALUES(1,3,'monitor-v1',?)").run(JSON.stringify(emptyData()));}this.migratePortal();this.assertVersion();this.db.exec('COMMIT');}catch(e){this.db.exec('ROLLBACK');this.db.close();throw e;}}
  private migratePortal(){let row;try{row=this.db.prepare('SELECT schema_version,model,payload FROM regstead_state WHERE id=1').get();}catch{throw new Error('Legacy development database: use a fresh M14.1 commercial database; existing data was not changed');}if(row?.schema_version===1&&row.model==='monitor-v1'){this.db.prepare('UPDATE regstead_state SET schema_version=2,payload=? WHERE id=1').run(migratePortalPayload(String(row.payload)));row={...row,schema_version:2,payload:migratePortalPayload(String(row.payload))};}if(row?.schema_version===2&&row.model==='monitor-v1')this.db.prepare('UPDATE regstead_state SET schema_version=3,payload=? WHERE id=1').run(migrateOperatorPayload(String(row.payload)));}
  private assertVersion(){let row;try{row=this.db.prepare('SELECT schema_version,model FROM regstead_state WHERE id=1').get();}catch{throw new Error('Legacy development database: use a fresh M14.1 commercial database; existing data was not changed');}if(row?.schema_version!==3||row.model!=='monitor-v1')throw new Error('Unsupported commercial schema/model');}
  async read():Promise<Data>{this.assertVersion();return JSON.parse(String(this.db.prepare('SELECT payload FROM regstead_state WHERE id=1').get()!.payload));}
  async transaction<T>(mutate:(data:Data)=>T):Promise<T>{this.db.exec('BEGIN IMMEDIATE');try{const data=JSON.parse(String(this.db.prepare('SELECT payload FROM regstead_state WHERE id=1').get()!.payload)) as Data;const result=mutate(data);if(result instanceof Promise)throw new Error('No async work inside transaction');validate(data);this.db.prepare('UPDATE regstead_state SET payload=? WHERE id=1').run(JSON.stringify(data));this.db.exec('COMMIT');return structuredClone(result);}catch(e){this.db.exec('ROLLBACK');throw e;}}
  async close(){this.db.close();}
}
export interface PgConnection {query(sql:string,values?:unknown[]):Promise<{rows:Record<string,unknown>[]}>;release():void}
export interface PgPool {connect():Promise<PgConnection>;end():Promise<void>}
export class PostgresCommercialRepository implements Repository {
  constructor(private pool:PgPool){}
  async migrate(){const c=await this.pool.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(741401)');await c.query(MIGRATION_1.replace('CREATE TABLE','CREATE TABLE IF NOT EXISTS'));await c.query("SELECT model FROM regstead_state LIMIT 0");await c.query("INSERT INTO regstead_state VALUES(1,3,'monitor-v1',$1) ON CONFLICT(id) DO NOTHING",[JSON.stringify(emptyData())]);const row=(await c.query('SELECT schema_version,model FROM regstead_state WHERE id=1')).rows[0];if(row.schema_version===1&&row.model==='monitor-v1'){const payload=(await c.query('SELECT payload FROM regstead_state WHERE id=1')).rows[0].payload;await c.query('UPDATE regstead_state SET schema_version=2,payload=$1 WHERE id=1',[migratePortalPayload(String(payload))]);row.schema_version=2;}if(row.schema_version===2&&row.model==='monitor-v1'){const payload=(await c.query('SELECT payload FROM regstead_state WHERE id=1')).rows[0].payload;await c.query('UPDATE regstead_state SET schema_version=3,payload=$1 WHERE id=1',[migrateOperatorPayload(String(payload))]);row.schema_version=3;}if(row.schema_version!==3||row.model!=='monitor-v1')throw new Error('Unsupported commercial migration version');await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');if((e as {code?:string}).code==='42703')throw new Error('Legacy development database: use a fresh M14.1 commercial database; existing data was not changed');throw e;}finally{c.release();}}
  async read(){const c=await this.pool.connect();try{return JSON.parse(String((await c.query('SELECT payload FROM regstead_state WHERE id=1')).rows[0].payload)) as Data;}finally{c.release();}}
  async transaction<T>(mutate:(data:Data)=>T):Promise<T>{const c=await this.pool.connect();try{await c.query('BEGIN');const data=JSON.parse(String((await c.query('SELECT payload FROM regstead_state WHERE id=1 FOR UPDATE')).rows[0].payload)) as Data;const result=mutate(data);if(result instanceof Promise)throw new Error('No async work inside transaction');validate(data);await c.query('UPDATE regstead_state SET payload=$1 WHERE id=1',[JSON.stringify(data)]);await c.query('COMMIT');return structuredClone(result);}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
  async close(){await this.pool.end();}
}
