import {expect,it} from 'vitest';
import {sampleServiceReview,compareServiceReviews,serviceCsv,parseServiceCsv,evidenceKey,type ServiceReviewItem,type ServiceDecision} from '../scripts/milestone10-review.js';
import {observePdfPage} from '../scripts/milestone10-structure.js';
function item(id='one',assignedServices=['probate']):ServiceReviewItem{return {id,evidenceKey:id,firm:'Firm '+id,sourceType:'PDF',url:'https://example.com/a.pdf',title:'Fees',referrers:[],ruleId:'PRICE-001',snippet:'Our fees are £900.',context:'Our fees are £900 for the work described here.',detectedServices:assignedServices,assignedServices,automatedAttribution:assignedServices.length===1?'SERVICE_SPECIFIC':'NO_SERVICE_CONTEXT',automatedAdjudication:'UNKNOWN',affectedResults:[],structure:observePdfPage(undefined,''),tags:['pricing']};}
function decision(label:ServiceDecision['label']='SERVICE_SPECIFIC_CORRECT',expectedServices=['probate']):ServiceDecision{return {itemId:'one',label,expectedServices,reviewer:'Fixture reviewer',reviewedAt:'2026-09-14',note:'Synthetic decision for testing only'};}
it('builds a deterministic separate sample excluding M9 source-equivalent evidence',()=>{const pool=Array.from({length:150},(_,i)=>item(String(i)));const excluded=new Set(['1','2']);const a=sampleServiceReview(pool,excluded),b=sampleServiceReview([...pool].reverse(),excluded);expect(a).toEqual(b);expect(a.items).toHaveLength(80);expect(a.items.some(i=>excluded.has(i.evidenceKey))).toBe(false);});
it('collapses duplicate source evidence even when rule identifiers differ',()=>{const a=item();const b={...item('other'),evidenceKey:a.evidenceKey,ruleId:'PRICE-002'};expect(sampleServiceReview([a,b],new Set()).sampleSize).toBe(1);});
it('normalizes whitespace but preserves PDF page identity in exclusion keys',()=>{expect(evidenceKey('url',1,'a  b')).toBe(evidenceKey('url',1,'a b'));expect(evidenceKey('url',1,'a b')).not.toBe(evidenceKey('url',2,'a b'));});
it('exports blank human decisions and hides adjudication while showing the proposed service',()=>{const csv=serviceCsv([item()]);expect(parseServiceCsv(csv)).toEqual([]);expect(csv).toContain('proposed_services');expect(csv).not.toContain('automated_adjudication');expect(csv).toBe(serviceCsv([item()]));});
it('neutralizes spreadsheet formulas in source titles',()=>{expect(serviceCsv([{...item(),title:'=HYPERLINK("bad")'}])).toContain("'=HYPERLINK");});
it('does not report agreement without human labels',()=>{expect(compareServiceReviews([item()],[]).exactAgreement.rate).toBeNull();});
it('requires both attribution class and expected service set for agreement',()=>{const d=decision('SERVICE_SPECIFIC_WRONG',['debt_recovery']);const r=compareServiceReviews([item()],[d]);expect(r.exactAgreement.rate).toBe(0);expect(r.falseServiceAssignment.rate).toBe(1);});
it('scores genuinely firm-wide evidence separately from service-specific evidence',()=>{const i={...item(),assignedServices:[],automatedAttribution:'FIRM_WIDE' as const};const r=compareServiceReviews([i],[decision('FIRM_WIDE',[])]);expect(r.byExpectedAttribution.FIRM_WIDE.rate).toBe(1);expect(r.falseServiceAssignment.rate).toBeNull();});
it('compares explicit multi-service sets independent of ordering',()=>{const i={...item(),assignedServices:['probate','debt_recovery'],automatedAttribution:'MULTI_SERVICE' as const};expect(compareServiceReviews([i],[decision('MULTI_SERVICE',['debt_recovery','probate'])]).exactAgreement.rate).toBe(1);});
it('counts unsupported additional service assignments',()=>{const i={...item(),assignedServices:['probate','debt_recovery'],automatedAttribution:'MULTI_SERVICE' as const};expect(compareServiceReviews([i],[decision('SERVICE_SPECIFIC_WRONG',['probate'])]).falseServiceAssignment.rate).toBe(1);});
it('measures abstention against human service-bearing cases',()=>{const i={...item(),assignedServices:[],automatedAttribution:'NO_SERVICE_CONTEXT' as const};expect(compareServiceReviews([i],[decision('SERVICE_SPECIFIC_WRONG',['probate'])]).overConservativeNoContext.rate).toBe(1);});
it.each(['missing reviewer','invalid date','missing service','duplicate','unknown id'])('rejects %s in review data',kind=>{const d=decision();if(kind==='missing reviewer')d.reviewer='';if(kind==='invalid date')d.reviewedAt='2026-02-30';if(kind==='missing service')d.expectedServices=[];if(kind==='unknown id')d.itemId='missing';expect(()=>compareServiceReviews([item()],kind==='duplicate'?[d,d]:[d])).toThrow();});
it('keeps human labels independent of automated objects',()=>{const i=item(),before=structuredClone(i);compareServiceReviews([i],[decision()]);expect(i).toEqual(before);});
it('does not score a contradictory WRONG label as agreement',()=>{expect(()=>compareServiceReviews([item()],[decision('SERVICE_SPECIFIC_WRONG',['probate'])])).toThrow('different service');});
it('scores corrections against immutable original labels, not a reinterpreted correct/wrong proposal',()=>{const i=item(),d=decision('SERVICE_SPECIFIC_WRONG',['debt_recovery']);const before=structuredClone(i);const report=compareServiceReviews([i],[d],{one:{state:'SERVICE_SPECIFIC',services:['debt_recovery'],reason:'LOCAL_CONTEXT'}});expect(report.exactAgreement.rate).toBe(1);expect(i).toEqual(before);});
it('requires every reassessment to be supplied',()=>{expect(()=>compareServiceReviews([item()],[decision()],{})).toThrow();});
