import { beforeEach,afterEach,expect,it,vi } from 'vitest';
import { mkdtempSync,rmSync,writeFileSync,readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { runCli } from '../src/cli/run.js';
import { SqliteRepository } from '../src/storage/sqlite.js';
import { universalPack } from '../src/rules/pack.js';
const fixture=vi.hoisted(()=>({version:'A' as 'A'|'B'}));
vi.mock('../src/crawler/http.js',async original=>({...await original<typeof import('../src/crawler/http.js')>(),createFetcher:()=>async(...args:Parameters<import('../src/crawler/http.js').Fetcher>)=>{const {rulesWebsite}=await import('./fixtures/milestone3.js');return rulesWebsite(fixture.version)(...args);}}));
let dir:string,db:string,output:ReturnType<typeof vi.spyOn>;
beforeEach(()=>{dir=mkdtempSync(join(tmpdir(),'watchlayer-rules-'));db=join(dir,'test.db');fixture.version='A';output=vi.spyOn(console,'log').mockImplementation(()=>{});vi.spyOn(console,'error').mockImplementation(()=>{});process.exitCode=0;});
afterEach(()=>{vi.restoreAllMocks();process.exitCode=0;rmSync(dir,{recursive:true,force:true});});
const text=()=>output.mock.calls.map((c:unknown[])=>String(c[0])).join('\n');
const scan=async()=>{await runCli('scan',['example.com','--db',db,'--rules','--json','--recheck-budget','1']);const data=JSON.parse(text());output.mockClear();return data;};
it('scans with rules and displays persisted findings without another scan',async()=>{await scan();fixture.version='B';const b=await scan();await runCli('findings',['example.com','--db',db]);expect(text()).toContain('POTENTIAL_ISSUE');expect(text()).toContain('UNKNOWN');output.mockClear();await runCli('findings',['example.com','--db',db,'--json']);expect(JSON.parse(text()).runs[0].scanId).toBe(b.snapshot.scanId);expect(process.exitCode).toBe(0);});
it('evaluates a stored scan by ID and exports versioned JSON',async()=>{const a=await scan();const path=join(dir,'rules.json');await runCli('rules',[a.snapshot.scanId,'--db',db,'--output',path]);const report=JSON.parse(readFileSync(path,'utf8'));expect(report.schemaVersion).toBe(1);expect(report.runs[0].results.length).toBeGreaterThanOrEqual(15);expect(process.exitCode).toBe(0);});
it('evaluates latest URL and loads custom versioned pack data',async()=>{await scan();const pack=structuredClone(universalPack);pack.version='1.1';const path=join(dir,'pack.json');writeFileSync(path,JSON.stringify(pack));await runCli('rules',['example.com','--db',db,'--pack',path,'--json']);expect(JSON.parse(text()).runs[0].packVersion).toBe('1.1');});
it('rejects incompatible packs before scanning',async()=>{const path=join(dir,'pack.json');writeFileSync(path,JSON.stringify({...universalPack,engineVersion:'99'}));await runCli('scan',['example.com','--db',db,'--rules','--pack',path]);expect(process.exitCode).toBe(1);});
it('rejects rules without persistence',async()=>{await runCli('scan',['example.com','--no-persist','--rules']);expect(process.exitCode).toBe(1);expect(console.error).toHaveBeenCalledWith('WatchLayer: --rules requires persistence');});
it('returns a clear error for missing stored scans',async()=>{await runCli('rules',['scan_missing','--db',db]);expect(process.exitCode).toBe(1);expect(console.error).toHaveBeenCalledWith('WatchLayer: Scan not found: scan_missing');});
it('does not display stale findings for a newer scan without rules',async()=>{await scan();await runCli('scan',['example.com','--db',db]);output.mockClear();await runCli('findings',['example.com','--db',db]);expect(text()).toContain('No stored rule runs');});
it('prevents updating or deleting historical runs, results and findings at SQL level',async()=>{const a=await scan();const raw=new DatabaseSync(db);try{for(const table of ['rule_runs','rule_results','findings']){expect(()=>raw.exec(`DELETE FROM ${table}`)).toThrow(/immutable/);expect(()=>raw.exec(`UPDATE ${table} SET data_json='{}'`)).toThrow(/immutable/);}}finally{raw.close();}const repository=new SqliteRepository(db);try{expect(repository.ruleRuns(a.snapshot.scanId)).toHaveLength(1);}finally{repository.close();}});
it('evaluates an older scan without using future scans as its baseline',async()=>{const a=await scan();fixture.version='B';await scan();await runCli('rules',[a.snapshot.scanId,'--db',db,'--json']);expect(JSON.parse(text()).runs[0].previousScanId).toBeNull();});
