import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {mkdtemp,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import Stripe from 'stripe';
import {SqliteCommercialRepository,MIGRATION_1,DOWN_1,validate,PostgresCommercialRepository,type PgPool} from '../src/regstead/repository.js';
import {Operations,versions,authenticate,entitled} from '../src/regstead/operations.js';
import {Worker,claim,LEASE_MS} from '../src/regstead/worker.js';
import {Billing,StripeProvider,type BillingConfig,type BillingProvider,type SubscriptionTruth} from '../src/regstead/billing.js';
import {FileArtifactStore,releaseReport,renderReport,evidenceDetails} from '../src/regstead/reports.js';
import {Notifications,SpoolEmailProvider} from '../src/regstead/notifications.js';
import {configuration,readiness} from '../src/regstead/config.js';
import {OperationalError,type Engine,type EngineResult,type Webhook,emptyData,type Repository} from '../src/regstead/types.js';
import type {Result} from '../src/rules/types.js';
const epoch=Date.parse('2026-09-28T12:00:00Z'),v=versions('1f45cc3f648bbd8d70e538f25ef29ba397e35dcf');
const cfg:BillingConfig={productId:'prod_regstead_fixture',monitorPriceId:'price_monitor_fixture',baseUrl:'https://regstead.example',termsVersion:'beta-v1',graceMs:86400000,liveMode:false};
const result=(status:Result['status']='UNKNOWN'):Result=>({schemaVersion:1,ruleId:'LAW-U001',ruleVersion:'1.8',packId:'lawwatch-england-wales',packVersion:'1.8',status,severity:'HIGH',confidence:'LOW',confidenceReason:'Bounded observation',applicability:'uncertain',title:'SRA number',explanation:'Could not confirm the number from the available public evidence.',resource:'https://firm.example',evidence:[{scanId:'scan_fixture',url:'https://firm.example/regulatory',observed:{sourceType:'STATIC_HTML'},explanation:'Selected public source.'}]});
const engineResult=():EngineResult=>({scanId:'scan_fixture',reference:'fixture.db',sourceProfile:'static-v1',comparisonBaseline:null,metrics:{pages:1,browserAttempts:0,unknown:1},results:[result(),result('PASS')],changes:[],startedAt:new Date(epoch).toISOString(),completedAt:new Date(epoch+1000).toISOString(),versions:v});
class FakeBilling implements BillingProvider {
  calls=0; truth!:SubscriptionTruth;
  async checkout(c:{id:string}){this.calls++;return {id:'cs_'+c.id,url:'https://checkout.stripe.com/fixture'};}
  async billingPortal(){return 'https://billing.stripe.com/fixture';}
  async subscription(){return structuredClone(this.truth);}
  verify(body:Buffer,signature:string){if(signature!=='fixture-verified')throw new Error('Invalid signature');return JSON.parse(body.toString()) as Webhook;}
}
let repo:SqliteCommercialRepository,ops:Operations,now:number,provider:FakeBilling,billing:Billing,root:string;
beforeEach(async()=>{root=await mkdtemp(join(tmpdir(),'watchlayer-m14-'));repo=new SqliteCommercialRepository(join(root,'commercial.db'));now=epoch;ops=new Operations(repo,v,()=>now,async()=>[{address:'93.184.216.34',family:4}]);provider=new FakeBilling();billing=new Billing(repo,provider,cfg,v,()=>now);});
afterEach(async()=>{await repo.close();});
async function onboard(n=1){return ops.onboard({legalName:`Fixture ${n}`,contactName:'Reviewer fixture',contactEmail:`person${n}@example.org`,url:`https://firm${n}.example`,cadenceMs:3600000,pack:'lawwatch-england-wales',packConfirmed:true,sectorApplicability:'ESTABLISHED'},'operator');}
async function activate(){const x=await onboard();const checkout=await billing.checkout(x.organisation.id,'beta-v1','operator');provider.truth={id:'sub_fixture',customerId:'cus_fixture',priceId:checkout.priceId,productId:cfg.productId,status:'active',periodEnd:now+30*86400000,cancelAtPeriodEnd:false,metadata:{product:'regstead',organisationId:x.organisation.id,checkoutId:checkout.id},quantity:1,currency:'gbp',amount:1699,interval:'month'};await event('evt_checkout','checkout.session.completed',checkout.id);return x;}
async function event(id:string,type:string,checkoutId?:string){await billing.receive(Buffer.from(JSON.stringify({id,type,created:Math.floor(now/1000),subscriptionId:'sub_fixture',checkoutId,status:'QUEUED',attempts:0})),'fixture-verified');await billing.processOne();}
async function draft(){await new Worker(repo,{run:async()=>engineResult()},()=>now).once();return (await repo.read()).reports[0];}
async function approve(reportId:string){const report=(await repo.read()).reports.find(r=>r.id===reportId)!;for(const f of report.findings)await ops.review(reportId,f.id,'APPROVED','Reviewed source context.','Clive');}
describe('M14 standard subscription lifecycle',()=>{
  it('completes the 18-step paid lifecycle without a real provider',async()=>{const x=await activate();expect((await repo.read()).jobs).toHaveLength(1);const report=await draft();expect((await repo.read()).jobs[0].status).toBe('AWAITING_REVIEW');const store=new FileArtifactStore(join(root,'reports'));await expect(releaseReport(repo,store,report.id,'Clive',now)).rejects.toThrow('Every finding');expect((await repo.read()).notifications.filter(n=>n.reportId)).toHaveLength(0);await approve(report.id);const released=await releaseReport(repo,store,report.id,'Clive',now);expect(released.hash).toMatch(/^[a-f0-9]{64}$/);const original=await store.get(released.artifact!);const mail=new Notifications(repo,new SpoolEmailProvider(join(root,'mail')),()=>now);while(await mail.once()){}expect((await repo.read()).notifications.every(n=>n.status==='SENT')).toBe(true);now+=3600001;expect(await ops.schedule()).toBe(1);await event('evt_paid','invoice.paid');expect(entitled(await repo.read(),x.organisation.id,now)).toBe(true);provider.truth.status='past_due';await event('evt_failed','invoice.payment_failed');expect((await repo.read()).subscriptions[0].graceDeadline).toBe(now+cfg.graceMs);provider.truth.status='canceled';await event('evt_cancel','customer.subscription.deleted');now+=86400000;expect(await ops.schedule()).toBe(0);const data=await repo.read();expect(data.jobs.filter(j=>j.type==='MONITORING').every(j=>j.status==='CANCELLED')).toBe(true);expect(await store.get(released.artifact!)).toEqual(original);expect(data.reports[0].status).toBe('RELEASED');expect(data.subscriptions).toHaveLength(1);});
  it('keeps UNKNOWN as uncertainty and escapes customer supplied markup',async()=>{await onboard();const report=await draft();await ops.review(report.id,report.findings[0].id,'ANNOTATED','Context remains limited.','Clive','<script>alert(1)</script>');await ops.review(report.id,report.findings[1].id,'SUPPRESSED','Duplicate context.','Clive');const html=renderReport(await repo.read(),report);expect(html).toContain('Could not confirm');expect(html).toContain('&lt;script&gt;');expect(html).not.toContain('<script>');expect(html).not.toMatch(/\b(non-compliant|illegal|breach)\b/i);expect((await repo.read()).runs[0].results).toEqual(engineResult().results);});
  it('requires every finding to be reviewed and blocks editing released reports',async()=>{await onboard();const r=await draft();await ops.review(r.id,r.findings[0].id,'APPROVED','Checked','Clive');await expect(releaseReport(repo,new FileArtifactStore(root),r.id,'Clive')).rejects.toThrow();await approve(r.id);await releaseReport(repo,new FileArtifactStore(root),r.id,'Clive');await expect(ops.review(r.id,r.findings[0].id,'SUPPRESSED','Later','Clive')).rejects.toThrow();});
  it('does not emit material notifications for suppressed serious findings',async()=>{await onboard();await new Worker(repo,{run:async()=>({...engineResult(),results:[result('POTENTIAL_ISSUE')]})},()=>now).once();const r=(await repo.read()).reports[0];await ops.review(r.id,r.findings[0].id,'SUPPRESSED','Not supported','Clive');await releaseReport(repo,new FileArtifactStore(root),r.id,'Clive');expect((await repo.read()).notifications.some(n=>n.template==='MATERIAL_REVIEW')).toBe(false);});
  it('emits reviewed material notification only after release',async()=>{await onboard();await new Worker(repo,{run:async()=>({...engineResult(),results:[result('POTENTIAL_ISSUE')]})},()=>now).once();const r=(await repo.read()).reports[0];await approve(r.id);expect((await repo.read()).notifications.some(n=>n.template==='MATERIAL_REVIEW')).toBe(false);await releaseReport(repo,new FileArtifactStore(root),r.id,'Clive');expect((await repo.read()).notifications.filter(n=>n.template==='MATERIAL_REVIEW')).toHaveLength(1);});
});
describe('M14 idempotency and worker fencing',()=>{
  it('deduplicates checkout creation and duplicate checkout/invoice events',async()=>{const x=await activate();await event('evt_checkout','checkout.session.completed');await event('evt_paid','invoice.paid');await event('evt_paid','invoice.paid');const d=await repo.read();expect(d.subscriptions).toHaveLength(1);expect(d.jobs).toHaveLength(1);expect(d.webhooks).toHaveLength(2);});
  it('reuses pending checkout sessions and records local terms',async()=>{const x=await onboard();const a=await billing.checkout(x.organisation.id,'beta-v1','operator');const b=await billing.checkout(x.organisation.id,'beta-v1','operator');expect(a).toEqual(b);expect(provider.calls).toBe(1);expect(a.acceptedAt).toBe(now);});
  it('claims one job once across database connections',async()=>{await onboard();const second=new SqliteCommercialRepository(join(root,'commercial.db'));try{const claims=await Promise.all([claim(repo,now),claim(second,now)]);expect(claims.filter(Boolean)).toHaveLength(1);}finally{await second.close();}});
  it('recovers abandoned running jobs and fences a stale claimant',async()=>{await onboard();const first=(await claim(repo,now))!;now+=LEASE_MS+1;const second=(await claim(repo,now))!;expect(second.job.token).not.toBe(first.job.token);expect(second.job.retryCount).toBe(1);});
  it('reuses a durable scan checkpoint after crash before draft publication',async()=>{const x=await onboard();await repo.transaction(d=>{d.runs.push({...engineResult(),id:'run-checkpoint',jobId:x.job.id,createdAt:now});});const run=vi.fn(async()=>engineResult());await new Worker(repo,{run},()=>now).once();expect(run).not.toHaveBeenCalled();expect((await repo.read()).reports).toHaveLength(1);});
  it('retries transient errors within a bounded limit',async()=>{await onboard();const run=vi.fn(async()=>{throw new OperationalError('NETWORK_TRANSIENT',true);});const w=new Worker(repo,{run},()=>now);for(let i=0;i<3;i++){await w.once();now+=600000;}expect(run).toHaveBeenCalledTimes(3);expect((await repo.read()).jobs[0]).toMatchObject({status:'FAILED',retryCount:2,failureCode:'NETWORK_TRANSIENT'});});
  it('does not retry permanent errors automatically',async()=>{await onboard();await new Worker(repo,{run:async()=>{throw new OperationalError('ENGINE_FAILURE');}},()=>now).once();expect((await repo.read()).jobs[0]).toMatchObject({status:'FAILED',retryCount:0});});
  it('operator retry preserves job identity',async()=>{const x=await onboard();await repo.transaction(d=>{d.jobs[0].status='FAILED';});await ops.retry(x.job.id,'Clive');expect((await repo.read()).jobs[0].id).toBe(x.job.id);});
  it('schedules at most one bounded catch-up without overlapping review',async()=>{await activate();now+=4000000;expect(await ops.schedule()).toBe(0);const r=await draft();await approve(r.id);await releaseReport(repo,new FileArtifactStore(root),r.id,'Clive');now+=100000000;expect(await ops.schedule()).toBe(1);expect(await ops.schedule()).toBe(0);expect((await repo.read()).sites[0].nextRunAt).toBe(now+3600000);});
  it('deduplicates concurrent report release and notification creation',async()=>{await onboard();const r=await draft();await approve(r.id);const store=new FileArtifactStore(root);const releases=await Promise.all([releaseReport(repo,store,r.id,'Clive',now),releaseReport(repo,store,r.id,'Clive',now)]);expect(releases[0].hash).toBe(releases[1].hash);expect((await repo.read()).notifications.filter(n=>n.reportId===r.id)).toHaveLength(1);});
  it('sends one notification once under concurrent requests',async()=>{await onboard();const send=vi.fn(async()=> 'provider-reference');const mail=new Notifications(repo,{send},()=>now);await Promise.all([mail.once(),mail.once()]);await mail.once();expect(send).toHaveBeenCalledTimes(1);});
  it('recovers an email delivery crash using the same durable provider key',async()=>{await onboard();const spool=new SpoolEmailProvider(root);const d=await repo.read(),n=d.notifications[0];const sent=new Map<string,string>();const send=vi.fn(async(key:string)=>{sent.set(key,'same-reference');return sent.get(key)!;});await repo.transaction(d=>{Object.assign(d.notifications[0],{status:'SENDING',token:'dead',leaseUntil:now-1,attempts:1});});await new Notifications(repo,{send},()=>now).once();expect(send.mock.calls[0][0]).toBe(n.id);expect((await repo.read()).notifications[0].status).toBe('SENT');});
});
describe('M14 billing isolation and entitlement',()=>{
  it('old invoice delivery cannot resurrect a cancelled subscription',async()=>{await activate();provider.truth.status='canceled';await event('cancel','customer.subscription.deleted');provider.truth.status='active';await event('old-paid','invoice.paid');expect((await repo.read()).subscriptions[0].status).toBe('canceled');});
  it.each(['product','price','metadata'])('ignores unrelated Stripe %s',async(kind)=>{await activate();if(kind==='product')provider.truth.productId='prod_other';if(kind==='price')provider.truth.priceId='price_other';if(kind==='metadata')provider.truth.metadata.product='other';await event('unrelated','invoice.paid');expect((await repo.read()).webhooks.at(-1)?.status).toBe('IGNORED');});
  it.each(['currency','amount','quantity','interval'])('rejects invalid recurring %s',async(field)=>{await activate();Object.assign(provider.truth,{[field]:field==='amount'?10:field==='quantity'?2:field==='currency'?'usd':'year'});await event('invalid','invoice.paid');expect((await repo.read()).webhooks.at(-1)?.status).toBe('FAILED');});
  it('rejects unknown terms',async()=>{const x=await onboard();await expect(billing.checkout(x.organisation.id,'old-terms','Clive')).rejects.toThrow();expect((await repo.read()).checkouts).toHaveLength(0);});
  it('does not extend grace indefinitely through repeated failure events',async()=>{await activate();provider.truth.status='past_due';await event('failure1','invoice.payment_failed');const until=(await repo.read()).subscriptions[0].graceDeadline;now+=1000;await event('failure2','invoice.payment_failed');expect((await repo.read()).subscriptions[0].graceDeadline).toBe(until);now=until!+1;expect(entitled(await repo.read(),(await repo.read()).organisations[0].id,now)).toBe(false);});
  it('does not stop active entitlement merely because an old payment-failed event arrives',async()=>{await activate();await event('old-failed','invoice.payment_failed');expect((await repo.read()).subscriptions[0].status).toBe('active');});
  it('a period-end cancellation remains entitled until its paid-through time',async()=>{const x=await activate();provider.truth.cancelAtPeriodEnd=true;await event('update','customer.subscription.updated');expect(entitled(await repo.read(),x.organisation.id,now)).toBe(true);now=provider.truth.periodEnd+1;expect(entitled(await repo.read(),x.organisation.id,now)).toBe(false);});
  it('rejects spoofed webhook without persisting its body',async()=>{await expect(billing.receive(Buffer.from('{}'),'spoof')).rejects.toThrow();expect((await repo.read()).webhooks).toHaveLength(0);});
  it('checks official Stripe raw-body signatures, timestamp and mode',()=>{const secret='fixture-signing-secret';const stripe=new Stripe('fixture-api-key');const adapter=new StripeProvider('fixture-api-key',secret,cfg);const payload=JSON.stringify({id:'evt_signed',type:'invoice.paid',created:Math.floor(Date.now()/1000),livemode:false,data:{object:{parent:{subscription_details:{subscription:'sub_fixture'}}}}});const signature=stripe.webhooks.generateTestHeaderString({payload,secret});expect(adapter.verify(Buffer.from(payload),signature).subscriptionId).toBe('sub_fixture');expect(()=>adapter.verify(Buffer.from(payload+' '),signature)).toThrow();const old=stripe.webhooks.generateTestHeaderString({payload,secret,timestamp:1});expect(()=>adapter.verify(Buffer.from(payload),old)).toThrow();const live=payload.replace('"livemode":false','"livemode":true');expect(()=>adapter.verify(Buffer.from(live),stripe.webhooks.generateTestHeaderString({payload:live,secret}))).toThrow();});
});
describe('M14 security and persistence',()=>{
  it('authenticates operators and rejects absent/incorrect credentials',()=>{expect(()=>authenticate(undefined,'x'.repeat(32),'Clive')).toThrow('Unauthorized');expect(()=>authenticate('bad','x'.repeat(32),'Clive')).toThrow('Unauthorized');expect(authenticate('x'.repeat(32),'x'.repeat(32),'Clive')).toBe('Clive');});
  it.each(['file:///etc/passwd','http://u:p@example.org','http://example.org:8080'])('rejects unsafe URL %s',async(url)=>{await expect(ops.onboard({legalName:'x',contactName:'x',contactEmail:'x@example.org',url,cadenceMs:3600000,pack:'lawwatch-england-wales',packConfirmed:true,sectorApplicability:'ESTABLISHED'},'Clive')).rejects.toThrow();});
  it('uses the existing resolver to block private networks',async()=>{const secure=new Operations(repo,v,()=>now);await expect(secure.onboard({legalName:'x',contactName:'x',contactEmail:'x@example.org',url:'http://127.0.0.1',cadenceMs:3600000,pack:'lawwatch-england-wales',packConfirmed:true,sectorApplicability:'ESTABLISHED'},'Clive')).rejects.toThrow();});
  it('rejects SQL-shaped URL fields without executing SQL',async()=>{await onboard();await ops.pause("'; DROP TABLE regstead_state; --",true,'Clive').catch(()=>{});expect((await repo.read()).organisations).toHaveLength(1);});
  it('rolls back failed transactions',async()=>{await expect(repo.transaction(d=>{d.organisations.push({} as never);throw new Error('rollback');})).rejects.toThrow();expect((await repo.read()).organisations).toHaveLength(0);});
  it('persists and reopens commercial state independently of engine storage',async()=>{await onboard();const second=new SqliteCommercialRepository(join(root,'commercial.db'));expect((await second.read()).jobs).toHaveLength(1);await second.close();});
  it('supports migration up/down on an empty fixture database',()=>{const db=new DatabaseSync(':memory:');db.exec(MIGRATION_1);db.exec(DOWN_1);expect(db.prepare("SELECT name FROM sqlite_master WHERE name='regstead_state'").get()).toBeUndefined();db.exec(MIGRATION_1);db.close();});
  it('rejects immutable artifact overwrites and traversal',async()=>{const store=new FileArtifactStore(root);await store.put('one.html',Buffer.from('first'));await expect(store.put('one.html',Buffer.from('second'))).rejects.toThrow();await expect(store.get('../private')).rejects.toThrow();});
  it.each(['This is illegal','Your firm is non-compliant','This breaches the rules'])('blocks unsafe review wording: %s',async(note)=>{await onboard();const r=await draft();await expect(ops.review(r.id,r.findings[0].id,'ANNOTATED',note,'Clive')).rejects.toThrow();});
  it('readiness requires a current worker heartbeat',async()=>{const config=configuration({REGSTEAD_ADMIN_TOKEN:'x'.repeat(32),REGSTEAD_RELEASE:v.release,STRIPE_SECRET_KEY:'fixture-api-key',STRIPE_WEBHOOK_SECRET:'fixture-signing-secret',REGSTEAD_STRIPE_PRODUCT_ID:cfg.productId,REGSTEAD_STRIPE_MONITOR_PRICE_ID:cfg.monitorPriceId,EMAIL_PROVIDER:'resend',RESEND_API_KEY:'fixture',EMAIL_FROM:'mail@example.org'});expect((await readiness(repo,config,now)).ready).toBe(false);await repo.transaction(d=>{d.heartbeats.worker=now;});expect((await readiness(repo,config,now)).ready).toBe(true);});
  it('stores exact scan and job versions',async()=>{await onboard();await draft();const data=await repo.read();expect(data.jobs[0]).toMatchObject(v);expect(data.runs[0].versions).toEqual(v);});
  it('records email failures without changing scan evidence',async()=>{await onboard();await new Notifications(repo,{send:async()=>{throw new Error('provider secret should not be logged');}},()=>now).once();const d=await repo.read();expect(d.notifications[0]).toMatchObject({status:'FAILED',failureCode:'EMAIL_FAILURE'});expect(JSON.stringify(d)).not.toContain('provider secret');});
});

describe('M14 adverse operational boundaries',()=>{
  it('rejects release if the review changes while artifact storage is pending',async()=>{await onboard();const r=await draft();await approve(r.id);const store={put:async(key:string)=>{await ops.review(r.id,r.findings[0].id,'SUPPRESSED','New review decision','Clive');return key;},get:async()=>Buffer.from('')};await expect(releaseReport(repo,store,r.id,'Clive')).rejects.toThrow('Review changed');expect((await repo.read()).reports[0].status).toBe('DRAFT');expect((await repo.read()).notifications.some(n=>n.reportId)).toBe(false);});
  it('records storage failure without releasing or notifying',async()=>{await onboard();const r=await draft();await approve(r.id);await expect(releaseReport(repo,{put:async()=>{throw new Error('disk unavailable');},get:async()=>Buffer.from('')},r.id,'Clive')).rejects.toMatchObject({code:'STORAGE_FAILURE'});const d=await repo.read();expect(d.reports[0].status).toBe('DRAFT');expect(d.audit.at(-1)?.code).toBe('STORAGE_FAILURE');});
  it('cannot let a stale worker overwrite a newer successful run',async()=>{await onboard();let finish!:(r:EngineResult)=>void;let started!:()=>void;const entered=new Promise<void>(r=>{started=r;});const pending=new Promise<EngineResult>(r=>{finish=r;});const first=new Worker(repo,{run:async()=>{started();return pending;}},()=>now).once();await entered;now+=LEASE_MS+1;await new Worker(repo,{run:async()=>({...engineResult(),scanId:'scan_new'})},()=>now).once();finish({...engineResult(),scanId:'scan_stale'});await first;const d=await repo.read();expect(d.runs).toHaveLength(1);expect(d.runs[0].scanId).toBe('scan_new');expect(d.jobs[0].status).toBe('AWAITING_REVIEW');});
  it('uses least-recently-served organisation fairness',async()=>{const a=await onboard(1),b=await onboard(2);await repo.transaction(d=>{d.organisations.find(o=>o.id===a.organisation.id)!.lastClaimAt=now;});expect((await claim(repo,now))?.job.organisationId).toBe(b.organisation.id);});
  it('does not allow an unreviewed report notification to be sent even if queued',async()=>{await onboard();const r=await draft();await repo.transaction(d=>{d.notifications=[];d.notifications.push({id:'held',key:'held',organisationId:r.organisationId,reportId:r.id,template:'BASELINE_READY',status:'QUEUED',attempts:0});});const send=vi.fn(async()=> 'ref');expect(await new Notifications(repo,{send},()=>now).once()).toBe(false);expect(send).not.toHaveBeenCalled();});
  it('preserves provider idempotency after send succeeds but acknowledgement is lost',async()=>{await onboard();const delivered=new Map<string,string>();let calls=0;const provider={send:async(key:string)=>{calls++;if(!delivered.has(key))delivered.set(key,'provider-1');return delivered.get(key)!;}};let failAcknowledgement=true;const wrapper:Repository={read:()=>repo.read(),close:async()=>{},transaction:async mutate=>repo.transaction(d=>{const before=d.notifications[0]?.status;const value=mutate(d);if(failAcknowledgement&&before==='SENDING'&&d.notifications[0]?.status==='SENT'){failAcknowledgement=false;throw new Error('acknowledgement lost');}return value;})};const mail=new Notifications(wrapper,provider,()=>now);await mail.once();const n=(await repo.read()).notifications[0];expect(n.status).toBe('FAILED');await mail.retry(n.id);await mail.once();expect(calls).toBe(2);expect(delivered.size).toBe(1);expect((await repo.read()).notifications[0].providerReference).toBe('provider-1');});
  it('serializes subscription reconciliation while a provider request is in flight',async()=>{await activate();let finish!:(s:SubscriptionTruth)=>void;const original=provider.subscription.bind(provider);provider.subscription=()=>new Promise(r=>{finish=r;});await billing.receive(Buffer.from(JSON.stringify({id:'slow',type:'invoice.paid',created:1,subscriptionId:'sub_fixture',status:'QUEUED',attempts:0})),'fixture-verified');const pending=billing.processOne();await new Promise(r=>setTimeout(r,0));expect(await billing.processOne()).toBe(false);finish(await original());await pending;expect((await repo.read()).webhooks.at(-1)?.status).toBe('PROCESSED');});
  it('refuses a second active subscription for the organisation',async()=>{const x=await activate();await expect(billing.checkout(x.organisation.id,'beta-v1','Clive')).rejects.toThrow('Subscription already exists');});
  it('rejects billing linkage to another organisation',async()=>{await activate();provider.truth.metadata.organisationId='unrelated-org';await event('cross-org','invoice.paid');expect((await repo.read()).webhooks.at(-1)?.status).toBe('FAILED');expect((await repo.read()).subscriptions).toHaveLength(1);});
  it('preserves original review decisions as an append-only audit trail',async()=>{await onboard();const r=await draft();await ops.review(r.id,r.findings[0].id,'APPROVED','First decision','Reviewer A');await ops.review(r.id,r.findings[0].id,'SUPPRESSED','Second decision','Reviewer B');const d=await repo.read();expect(d.reviews.map(r=>r.reviewer)).toEqual(['Reviewer A','Reviewer B']);expect(d.runs[0].results[0]).toEqual(result());});
  it('does not treat partial UNKNOWN evidence as operational scan failure',async()=>{await onboard();await new Worker(repo,{run:async()=>({...engineResult(),metrics:{pages:1,failedPages:1,browserFailures:1,unknown:2}})},()=>now).once();expect((await repo.read()).jobs[0].status).toBe('AWAITING_REVIEW');});
});

it('validates the Regstead catalog before creating a hosted Checkout session',async()=>{
  const create=vi.fn(async()=>({id:'cs_fixture',url:'https://checkout.stripe.com/fixture'}));
  const retrieve=vi.fn(async()=>({id:cfg.monitorPriceId,product:'prod_other',active:true,currency:'gbp',unit_amount:1699,recurring:{interval:'month',interval_count:1}}));
  const sdk={prices:{retrieve},checkout:{sessions:{create}}} as unknown as Stripe;
  const adapter=new StripeProvider('fixture-api-key','fixture-signing-secret',cfg,sdk);const checkout={id:'checkout-fixture',organisationId:'org-fixture',priceId:cfg.monitorPriceId,termsVersion:'beta-v1',acceptedAt:epoch,createdAt:epoch};
  await expect(adapter.checkout(checkout,'fixture@example.org')).rejects.toMatchObject({code:'INVALID_CONFIGURATION'});expect(create).not.toHaveBeenCalled();
  retrieve.mockResolvedValue({id:cfg.monitorPriceId,product:cfg.productId,active:true,currency:'gbp',unit_amount:1699,recurring:{interval:'month',interval_count:1}});
  await adapter.checkout(checkout,'fixture@example.org');expect(create).toHaveBeenCalledOnce();const args=create.mock.calls[0] as unknown as [Record<string,unknown>,{idempotencyKey:string}];expect(args[0]).not.toHaveProperty('payment_method_types');expect(args[0]).toMatchObject({mode:'subscription',client_reference_id:checkout.id});expect(args[1].idempotencyKey).toContain(checkout.id);
});

it('retains bounded PDF page, rendered provenance and selected snippet context in reports',()=>{expect(evidenceDetails({facts:[{snippet:'Our fixed fee is £900.',source:{sourceType:'PDF',pageNumber:3,url:'https://example.org/fees.pdf'}},{observation:{sourceType:'RENDERED_DOM'}}]})).toContain('PDF page 3');expect(evidenceDetails({observation:{sourceType:'RENDERED_DOM'}})).toContain('Rendered website content');expect(evidenceDetails({snippet:'x'.repeat(5000)})).toHaveLength(1002);});
