import {request as httpRequest} from 'node:http';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {mkdtemp} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {DatabaseSync} from 'node:sqlite';
import {chromium} from 'playwright';
import {AdminAccess,ADMIN_LINK_MS,ADMIN_SESSION_MS} from '../src/regstead/admin-access.js';
import {AdminPortal,pilotMetrics} from '../src/regstead/admin-http.js';
import {SqliteCommercialRepository,MIGRATION_1} from '../src/regstead/repository.js';
import {Operations,digest,versions} from '../src/regstead/operations.js';
import {FileArtifactStore} from '../src/regstead/reports.js';
import {Notifications} from '../src/regstead/notifications.js';
import {httpService} from '../src/regstead/http.js';
import type {Billing} from '../src/regstead/billing.js';
import type {EmailProvider,OperatorUser} from '../src/regstead/types.js';
import type {Result} from '../src/rules/types.js';

let repo:SqliteCommercialRepository,access:AdminAccess,ops:Operations,root:string,now:number,user:OperatorUser,org:string,server:ReturnType<typeof httpService>|undefined,url:string;
const origin='https://portal.example',mail:{key:string;to:string;subject:string;text:string}[]=[];
const email:EmailProvider={send:async(key,message)=>{mail.push({key,...message});return 'accepted:'+key;}};
const billing={billingPortal:vi.fn(async()=> 'https://billing.stripe.com/p/operator'),retry:vi.fn(async(id:string,actor:string)=>repo.transaction(d=>{const event=d.webhooks.find(w=>w.id===id);if(!event||event.status!=='FAILED')throw new Error('Not failed');event.status='QUEUED';d.audit.push({id:'audit-webhook-'+id,event:'webhook_retry',at:now,actor});}))} as unknown as Billing;
const pack={pack:'lawwatch-england-wales' as const,packConfirmed:true as const,sectorApplicability:'ESTABLISHED' as const};
beforeEach(async()=>{root=await mkdtemp(join(tmpdir(),'watchlayer-m16-'));repo=new SqliteCommercialRepository(join(root,'commercial.db'));now=Date.parse('2026-10-01T09:00:00Z');mail.length=0;vi.clearAllMocks();ops=new Operations(repo,versions('a'.repeat(40)),()=>now,async()=>[{address:'93.184.216.34',family:4}]);org=(await ops.onboard({legalName:'Pilot Law LLP',contactName:'Pilot owner',contactEmail:'owner@example.org',url:'https://pilot.example',cadenceMs:86400000,...pack},'Bootstrap operator')).organisation.id;access=new AdminAccess(repo,email,origin,()=>now);user=await access.create('operator@example.org','Pilot Operator','Bootstrap operator');});
afterEach(async()=>{if(server){await new Promise<void>((resolve,reject)=>server!.close(error=>error?reject(error):resolve()));server=undefined;}await repo.close();});
const token=()=>new URL(mail.at(-1)!.text.match(/https:\/\/\S+/)![0]).searchParams.get('token')!;
async function login(){await access.request(user.email,'fixture');return access.verify(token(),'fixture');}
async function start(){const notifications=new Notifications(repo,email,origin,()=>now),admin=new AdminPortal(access,ops,new FileArtifactStore(root),billing,notifications,async()=>({ready:true,database:true,worker:true,engine:true,configuration:true,email:true}),'127.0.0.1',()=>now);server=httpService(undefined,async()=>({ready:true}),undefined,admin);await new Promise<void>(resolve=>server!.listen(0,'127.0.0.1',resolve));url='http://127.0.0.1:'+(server.address() as {port:number}).port;}
async function request(path:string,session?:{session:string;csrf:string},form?:Record<string,string>,extra:Record<string,string>={}){return new Promise<Response>((resolve,reject)=>{const req=httpRequest(url+path,{method:form?'POST':'GET',headers:{host:'portal.example','x-forwarded-proto':'https',...(session?{cookie:'__Host-regstead-admin-session='+session.session+'; __Host-regstead-admin-csrf='+session.csrf}:{}),...(form?{origin,'content-type':'application/x-www-form-urlencoded'}:{}),...extra}},res=>{const chunks:Buffer[]=[];res.on('data',chunk=>chunks.push(chunk));res.on('end',()=>{const headers=new Headers();for(const [key,value] of Object.entries(res.headers))if(value!==undefined)headers.set(key,Array.isArray(value)?value.join(', '):value);resolve(new Response(Buffer.concat(chunks),{status:res.statusCode!,headers}));});});req.on('error',reject);req.end(form?new URLSearchParams(form).toString():undefined);});}
async function draft(findings=2){const data=await repo.read(),job=data.jobs[0],reportId='report-fixture',runId='run-fixture';const raw=(index:number)=>({ruleId:index?'PRICE-008':'WEB-U004',ruleVersion:'1.8',packId:index?'lawwatch-england-wales':'watchlayer-universal',packVersion:'1.8',scope:'SITE',status:index?'UNKNOWN':'PASS',severity:index?'HIGH':'MEDIUM',confidence:index?'LOW':'HIGH',applicability:'applicable',serviceType:index?'residential_conveyancing':undefined,title:index?'VAT treatment':'Known page continuity',explanation:'Public evidence requires review',resource:'https://pilot.example/pricing',unknownReasonCodes:index?['INSUFFICIENT_CONTEXT']:undefined,evidence:[{url:'https://pilot.example/pricing',explanation:'Fixture evidence'}]} as unknown as Result);await repo.transaction(d=>{d.jobs[0].status='AWAITING_REVIEW';d.runs.push({id:runId,jobId:job.id,createdAt:now,scanId:'scan-fixture',reference:'fixture.db',sourceProfile:'fixture',comparisonBaseline:null,metrics:{pages:2},results:[],changes:[],startedAt:new Date(now-5000).toISOString(),completedAt:new Date(now).toISOString(),versions:versions('a'.repeat(40))});d.reports.push({id:reportId,jobId:job.id,scanRunId:runId,organisationId:org,siteId:job.siteId,version:1,status:'DRAFT',createdAt:now,findings:Array.from({length:findings},(_,index)=>({id:'finding-'+index,raw:raw(index),title:raw(index).title,explanation:raw(index).explanation}))});});return reportId;}

it('requires an explicit pack confirmation and records established applicability',async()=>{await expect(ops.onboard({legalName:'Unsafe',contactName:'A',contactEmail:'a@example.org',url:'https://other.example',cadenceMs:3600000,pack:'lawwatch-england-wales',packConfirmed:false,sectorApplicability:'ESTABLISHED'} as never,'Operator')).rejects.toThrow();const data=await repo.read();expect(data.sites[0]).toMatchObject({pack:'lawwatch-england-wales',sectorApplicability:'ESTABLISHED',packConfirmedBy:'Bootstrap operator'});expect(data.audit.some(a=>a.event==='pack_assignment_confirmed')).toBe(true);});
it('allows explicit NOT_ESTABLISHED only with a visible persisted warning state',async()=>{const created=await ops.onboard({legalName:'Investigate',contactName:'A',contactEmail:'a@other.example',url:'https://other.example',cadenceMs:3600000,pack:'lawwatch-england-wales',packConfirmed:true,sectorApplicability:'NOT_ESTABLISHED'},'Operator');expect(created.site.sectorApplicability).toBe('NOT_ESTABLISHED');});
it('stores operator link and session hashes, with shorter operator expiry',async()=>{await access.request(user.email,'client');const raw=token(),data=await repo.read();expect(data.operatorLinks[0].hash).toBe(digest(raw));expect(data.operatorLinks[0].expiresAt).toBe(now+ADMIN_LINK_MS);const session=await access.verify(raw,'client');expect((await repo.read()).operatorSessions[0].expiresAt).toBe(now+ADMIN_SESSION_MS);expect(JSON.stringify(await repo.read())).not.toContain(session.session);});
it('does not send a login link to an unregistered operator',async()=>{await access.request('unknown@example.org','client');expect(mail).toHaveLength(0);expect((await repo.read()).operatorUsers).toHaveLength(1);});
it('enforces single-use links, session rotation, expiry and disablement',async()=>{await access.request(user.email,'client');const raw=token(),first=await access.verify(raw,'client');await expect(access.verify(raw,'client')).rejects.toThrow();await access.request(user.email,'client');const second=await access.verify(token(),'client',first.session);await expect(access.authenticate(first.session)).rejects.toThrow();now+=ADMIN_SESSION_MS;await expect(access.authenticate(second.session)).rejects.toThrow();now-=ADMIN_SESSION_MS;await access.disable(user.id,'Bootstrap operator');await expect(access.authenticate(second.session)).rejects.toThrow();});
it('rate limits operator email and verification attempts separately',async()=>{for(let index=0;index<3;index++)await access.request(user.email,'client');await expect(access.request(user.email,'client')).rejects.toThrow('Rate limited');for(let index=0;index<20;index++)await access.verify('invalid','attacker').catch(()=>{});await expect(access.verify('invalid','attacker')).rejects.toThrow('Rate limited');});
it('requires authentication and emits strict security headers',async()=>{await start();const redirect=await request('/admin');expect(redirect.status).toBe(303);expect(redirect.headers.get('location')).toBe('/admin/login');const loginPage=await request('/admin/login');expect(loginPage.headers.get('content-security-policy')).toContain("default-src 'none'");expect(loginPage.headers.get('x-frame-options')).toBe('DENY');expect(loginPage.headers.get('set-cookie')).toMatch(/HttpOnly; Secure; SameSite=Strict/);});
it('rejects wrong origin, missing CSRF, unsafe host and insecure forwarding',async()=>{const session=await login();await start();expect((await request('/admin/logout',session,{csrf:session.csrf},{origin:'https://evil.example'})).status).toBe(400);expect((await request('/admin/logout',session,{})).status).toBe(400);expect((await request('/admin',session,undefined,{host:'evil.example'})).status).toBe(400);expect((await request('/admin',session,undefined,{'x-forwarded-proto':'http'})).status).toBe(400);});
it('dashboard reports readiness, queues, failures, schedules and pilot metrics',async()=>{await repo.transaction(d=>{d.heartbeats.worker=now;d.notifications.push({id:'failed-email',key:'failed-email',organisationId:org,template:'ONBOARDING',status:'FAILED',attempts:1});});const session=await login();await start();const html=await (await request('/admin',session)).text();expect(html).toContain('System readiness');expect(html).toContain('Pilot metrics');expect(html).toContain('failedEmails');expect(html).toContain('pilot.example');});
it('lists organisation identity, pack, monitoring, billing and released status without Stripe IDs',async()=>{await repo.transaction(d=>d.subscriptions.push({id:'sub',organisationId:org,provider:'stripe',stripeCustomerId:'cus_secret',stripeSubscriptionId:'sub_secret',stripePriceId:'price_secret',status:'past_due',currentPeriodEnd:now+10000,cancelAtPeriodEnd:false,createdAt:now,updatedAt:now,graceDeadline:now+5000,lastEventCreated:0}));const session=await login();await start();const html=await (await request('/admin/organisations/'+org,session)).text();expect(html).toContain('lawwatch-england-wales');expect(html).toContain('past_due');expect(html).not.toMatch(/cus_secret|sub_secret|price_secret/);});
it('provides dedicated billing and operations views without provider identifiers',async()=>{await repo.transaction(d=>{d.subscriptions.push({id:'sub',organisationId:org,provider:'stripe',stripeCustomerId:'cus_secret',stripeSubscriptionId:'sub_secret',stripePriceId:'price_secret',status:'past_due',currentPeriodEnd:now+10000,cancelAtPeriodEnd:false,createdAt:now,updatedAt:now,graceDeadline:now+5000,lastEventCreated:0});Object.assign(d.jobs[0],{status:'FAILED',failureCode:'NETWORK_TRANSIENT'});d.notifications.push({id:'failed-email',key:'failed-email',organisationId:org,template:'ONBOARDING',status:'FAILED',attempts:1});});const session=await login();await start();const billingPage=await (await request('/admin/billing',session)).text(),operationsPage=await (await request('/admin/operations',session)).text();expect(billingPage).toContain('past_due');expect(billingPage).toContain('Open Stripe Billing Portal');expect(billingPage).not.toMatch(/cus_secret|sub_secret|price_secret/);expect(operationsPage).toContain('NETWORK_TRANSIENT');expect(operationsPage).toContain('Retry eligible job');expect(operationsPage).toContain('Retry email');});
it('onboarding form makes pack assignment and uncertainty explicit',async()=>{const session=await login();await start();const html=await (await request('/admin/onboard',session)).text();expect(html).toContain('Pack safeguard');expect(html).toContain('NOT ESTABLISHED');expect(html).toContain('explicitly confirm');});
it('rejects admin onboarding without pack confirmation',async()=>{const session=await login();await start();const response=await request('/admin/onboard',session,{csrf:session.csrf,legalName:'Missing confirmation',contactName:'A',contactEmail:'a@missing.example',url:'https://missing.example',cadenceMs:'3600000',sectorApplicability:'ESTABLISHED'});expect(response.status).toBe(400);expect((await repo.read()).organisations).toHaveLength(1);});
it('records an individually audited decision and exposes source, service and first-baseline context',async()=>{const report=await draft(),session=await login();await start();const page=await (await request('/admin/review/'+report,session)).text();expect(page).toContain('First baseline');expect(page).toContain('residential_conveyancing');expect(page).toContain('pilot.example/pricing');expect((await request('/admin/review/'+report+'/finding-0',session,{csrf:session.csrf,status:'APPROVED',note:'Checked source evidence'})).status).toBe(303);const data=await repo.read();expect(data.reviews).toHaveLength(1);expect(data.audit.at(-1)?.event).toBe('finding_reviewed');});
it('has no bulk approval endpoint and release remains blocked until every finding is reviewed',async()=>{const report=await draft(),session=await login();await start();expect((await request('/admin/review/'+report+'/bulk',session,{csrf:session.csrf,status:'APPROVED',note:'bulk'})).status).toBe(400);await ops.review(report,'finding-0','APPROVED','Checked','Operator');expect((await request('/admin/reports/'+report+'/release',session,{csrf:session.csrf,confirm:'RELEASE'})).status).toBe(400);expect((await repo.read()).reports[0].status).toBe('DRAFT');});
it('requires typed confirmation before immutable release',async()=>{const report=await draft(1),session=await login();await ops.review(report,'finding-0','APPROVED','Checked','Operator');await start();expect((await request('/admin/reports/'+report+'/release',session,{csrf:session.csrf,confirm:'yes'})).status).toBe(400);expect((await request('/admin/reports/'+report+'/release',session,{csrf:session.csrf,confirm:'RELEASE'})).status).toBe(303);const released=(await repo.read()).reports[0];expect(released.status).toBe('RELEASED');expect(released.hash).toMatch(/^[a-f0-9]{64}$/);expect((await repo.read()).audit.some(a=>a.event==='report_released')).toBe(true);});
it('views and downloads only hash-valid released customer artifacts',async()=>{const report=await draft(1),session=await login();await ops.review(report,'finding-0','APPROVED','Checked','Operator');await start();await request('/admin/reports/'+report+'/release',session,{csrf:session.csrf,confirm:'RELEASE'});for(const suffix of ['', '/download']){const response=await request('/admin/reports/'+report+suffix,session);expect(response.status).toBe(200);expect(response.headers.get('content-security-policy')).toContain('sandbox');expect(response.headers.get('content-disposition')).toContain(suffix?'attachment':'inline');}await repo.transaction(d=>{d.reports[0].hash='bad';});expect((await request('/admin/reports/'+report,session)).status).toBe(400);});
it('pause and resume use existing operations and audit boundaries',async()=>{const session=await login(),site=(await repo.read()).sites[0];await start();expect((await request('/admin/sites/'+site.id+'/pause',session,{csrf:session.csrf})).status).toBe(303);expect((await repo.read()).sites[0].paused).toBe(true);await request('/admin/sites/'+site.id+'/resume',session,{csrf:session.csrf});expect((await repo.read()).sites[0].paused).toBe(false);expect((await repo.read()).audit.filter(a=>a.event.startsWith('monitoring_'))).toHaveLength(2);});
it('retries only eligible job, webhook and email failures with audit records',async()=>{await repo.transaction(d=>{Object.assign(d.jobs[0],{status:'FAILED',failureCode:'NETWORK_TRANSIENT'});d.webhooks.push({id:'webhook-failed',type:'invoice.paid',created:1,status:'FAILED',attempts:1});d.notifications.push({id:'email-failed',key:'email-failed',organisationId:org,template:'ONBOARDING',status:'FAILED',attempts:1});});const session=await login();await start();for(const path of ['/admin/jobs/'+(await repo.read()).jobs[0].id+'/retry','/admin/webhooks/webhook-failed/retry','/admin/notifications/email-failed/retry'])expect((await request(path,session,{csrf:session.csrf})).status).toBe(303);const data=await repo.read();expect(data.jobs[0].status).toBe('QUEUED');expect(data.webhooks[0].status).toBe('QUEUED');expect(data.notifications.find(n=>n.id==='email-failed')?.status).toBe('QUEUED');expect(data.audit.map(a=>a.event)).toEqual(expect.arrayContaining(['job_retry_requested','webhook_retry','email_retry_requested']));});
it('opens billing portal from the server-side organisation link and rejects unsafe redirects',async()=>{await repo.transaction(d=>d.subscriptions.push({id:'sub',organisationId:org,provider:'stripe',stripeCustomerId:'cus_secret',stripeSubscriptionId:'sub_secret',stripePriceId:'price_secret',status:'active',currentPeriodEnd:now+10000,cancelAtPeriodEnd:false,createdAt:now,updatedAt:now,lastEventCreated:0}));const session=await login();await start();const response=await request('/admin/billing/'+org+'/manage',session,{csrf:session.csrf,customerId:'attacker'});expect(response.status).toBe(303);expect(billing.billingPortal).toHaveBeenCalledWith(org);vi.mocked(billing.billingPortal).mockResolvedValueOnce('https://evil.example');expect((await request('/admin/billing/'+org+'/manage',session,{csrf:session.csrf})).status).toBe(400);});
it('derives pilot metrics without customer analytics',async()=>{const report=await draft(1);await ops.review(report,'finding-0','SUPPRESSED','Not relevant','Operator');await repo.transaction(d=>{d.reports[0].releasedAt=now+1000;d.notifications.push({id:'sent',key:'sent',organisationId:org,template:'ONBOARDING',status:'SENT',attempts:1});d.jobs[0].retryCount=2;});expect(pilotMetrics(await repo.read(),now+2000)).toMatchObject({scanCount:1,averageScanDurationMs:5000,findingsReviewed:1,suppressed:1,emailAccepted:1,jobRetries:2});});
it('migrates schema 2 operator state without changing existing commercial history',async()=>{const file=join(root,'schema2.db'),db=new DatabaseSync(file),data=await repo.read();db.exec(MIGRATION_1);const {operatorUsers,operatorLinks,operatorSessions,...schema2}=data;db.prepare("INSERT INTO regstead_state VALUES(1,2,'monitor-v1',?)").run(JSON.stringify(schema2));db.close();const migrated=new SqliteCommercialRepository(file);try{const restored=await migrated.read();expect(restored.organisations).toEqual(data.organisations);expect(restored.operatorUsers).toEqual([]);const check=new DatabaseSync(file);expect(check.prepare('SELECT schema_version FROM regstead_state').get()?.schema_version).toBe(3);check.close();}finally{await migrated.close();}});
it('renders usable operator dashboard and review queue at 390px and desktop widths',async()=>{await draft(1);await start();for(const width of [390,1280]){const session=await login(),browser=await chromium.launch({headless:true});try{const context=await browser.newContext({viewport:{width,height:900}});await context.route(origin+'/**',async route=>{const incoming=route.request(),parsed=new URL(incoming.url()),headers=await incoming.allHeaders(),response=await request(parsed.pathname+parsed.search,session,incoming.method()==='POST'?Object.fromEntries(new URLSearchParams(incoming.postData()??'')):undefined,{...headers,host:'portal.example','x-forwarded-proto':'https'});const redirect=response.status===303?response.headers.get('location'):null;response.headers.delete('content-length');response.headers.delete('transfer-encoding');await route.fulfill({status:redirect?200:response.status,headers:Object.fromEntries(response.headers),body:redirect?`<meta http-equiv="refresh" content="0;url=${redirect}">`:Buffer.from(await response.arrayBuffer())});});const page=await context.newPage();await page.goto(origin+'/admin');await page.getByRole('heading',{name:'Pilot operations'}).waitFor();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.goto(origin+'/admin/review');await page.getByRole('heading',{name:'Review queue'}).waitFor();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`reports/milestone16/admin-${width}.png`,fullPage:true});}finally{await browser.close();}}},40000);
