import {expect,it,vi} from 'vitest';
import {customerCounts,customerLabels,customerReportView} from '../src/regstead/customer-presentation.js';
import {renderReport,releaseReport} from '../src/regstead/reports.js';
import {emptyData,type ArtifactStore,type Data,type Report,type Repository} from '../src/regstead/types.js';
import type {Result,State} from '../src/rules/types.js';

const now=Date.parse('2026-10-01T10:00:00Z');
const result=(status:State,ruleId:string,title:string):Result=>({schemaVersion:1,ruleId,ruleVersion:'1.8',packId:'lawwatch-england-wales',packVersion:'1.8',status,severity:status==='POTENTIAL_ISSUE'?'HIGH':'MEDIUM',confidence:status==='UNKNOWN'?'LOW':'HIGH',confidenceReason:'Fixture evidence',applicability:'applicable',title,explanation:`${title} explanation`,resource:'https://firm.example/pricing',evidence:[{scanId:'scan-current',previousScanId:'scan-before',url:'https://firm.example/pricing',explanation:'Public page observation',observed:{sourceType:'RENDERED_DOM',snippet:'Evidence excerpt'}}]});
function fixture(kind:'BASELINE'|'MONITORING'='BASELINE'){
  const data=emptyData(),findings=[result('PASS','LAW-U001','SRA number detected'),result('WARNING','LAW-C005','Pricing information changed'),result('UNKNOWN','PRICE-010','VAT treatment of disbursements'),result('POTENTIAL_ISSUE','WEB-U001','Important availability change')].map((raw,index)=>({id:'finding-'+index,raw,title:raw.title,explanation:raw.explanation}));
  Object.assign(data,{organisations:[{id:'org',legalName:'Example Law LLP',displayName:'Example Law',contactName:'Owner',contactEmail:'owner@example.org',notes:'',status:'ACTIVE',createdAt:now-90_000,updatedAt:now}],sites:[{id:'site',organisationId:'org',canonicalUrl:'https://firm.example/',hostname:'firm.example',active:true,paused:false,pack:'lawwatch-england-wales',browserFallback:true,createdAt:now-90_000,updatedAt:now,nextRunAt:now+86_400_000,cadenceMs:86_400_000}],jobs:[{id:'job',key:'job',organisationId:'org',siteId:'site',type:kind,status:'APPROVED',scheduledAt:now-10_000,retryCount:0,engineVersion:'1',packVersion:'1.8',browserPolicyVersion:'1.3',release:'fixture'}],runs:[{id:'run',jobId:'job',createdAt:now,scanId:'scan-current',reference:'fixture',sourceProfile:'fixture',comparisonBaseline:kind==='MONITORING'?'scan-before':null,metrics:{},results:findings.map(f=>f.raw),changes:kind==='MONITORING'?[findings[1].raw,findings[3].raw]:[],startedAt:new Date(now-5000).toISOString(),completedAt:new Date(now).toISOString(),versions:{engineVersion:'1',packVersion:'1.8',browserPolicyVersion:'1.3',release:'fixture'}}]});
  const report:Report={id:'report',jobId:'job',scanRunId:'run',organisationId:'org',siteId:'site',version:1,status:'DRAFT',createdAt:now,findings};data.reports.push(report);data.reviews.push(...findings.map((f,index)=>({id:'review-'+index,reportId:'report',findingId:f.id,status:index===3?'SUPPRESSED' as const:'APPROVED' as const,reviewer:'Operator',reviewedAt:now,note:'Evidence checked'})));return {data,report};
}
class MemoryRepository implements Repository {constructor(public data:Data){}async read(){return structuredClone(this.data);}async transaction<T>(fn:(d:Data)=>T){const value=fn(this.data);return structuredClone(value);}async close(){}}
class MemoryStore implements ArtifactStore {items=new Map<string,Buffer>();put=vi.fn(async(key:string,body:Buffer)=>{this.items.set(key,body);return key;});async get(key:string){return this.items.get(key)!;}}

it('documents an exact presentation-only status mapping',()=>{expect(customerLabels).toEqual({PASS:'Confirmed',WARNING:'Review recommended',POTENTIAL_ISSUE:'Action recommended',UNKNOWN:'Could not confirm',NOT_APPLICABLE:'Not applicable'});});
it('counts only released customer-visible reviewed findings',()=>{const {data,report}=fixture();const view=customerReportView(data,report);expect(customerCounts(view.findings)).toEqual({PASS:1,WARNING:1,POTENTIAL_ISSUE:0,UNKNOWN:1,NOT_APPLICABLE:0});expect(view.attentionCount).toBe(1);});
it('distinguishes a baseline without implying comparison history',()=>{const {data,report}=fixture();expect(customerReportView(data,report)).toMatchObject({kind:'Baseline',isBaseline:true,relationship:'Baseline established',changeCount:0});expect(renderReport(data,report)).toContain('Baseline established');});
it('derives monitoring changes from visible comparison results only',()=>{const {data,report}=fixture('MONITORING'),view=customerReportView(data,report);expect(view).toMatchObject({kind:'Monitoring',isBaseline:false,relationship:'Compared with the preceding monitored observation',changeCount:1});});
it('orders attention, uncertainty and confirmed observations without changing raw states',()=>{const {data,report}=fixture('MONITORING'),html=renderReport(data,report);expect(html.indexOf('Pricing information changed')).toBeLessThan(html.indexOf('VAT treatment of disbursements'));expect(html.indexOf('VAT treatment of disbursements')).toBeLessThan(html.indexOf('SRA number detected'));expect(html).toContain('Raw engine status');expect(html).toContain('WARNING');expect(report.findings.map(f=>f.raw.status)).toEqual(['PASS','WARNING','UNKNOWN','POTENTIAL_ISSUE']);});
it('presents UNKNOWN neutrally with evidence and no absence conclusion',()=>{const {data,report}=fixture(),html=renderReport(data,report);expect(html).toContain('Could not confirm');expect(html).toContain('This does not necessarily mean the information is absent.');expect(html).toContain('Evidence excerpt');expect(html).not.toContain('non-compliant');});
it('marks human editorial review without claiming compliance certification',()=>{const {data,report}=fixture(),html=renderReport(data,report);expect(html).toContain('Human reviewed before release');expect(html).not.toMatch(/verified compliant|approved for compliance|legally checked/i);});
it('includes deliberate A4 print treatment and colour-independent status text',()=>{const {data,report}=fixture(),html=renderReport(data,report);expect(html).toContain('@page{size:A4');expect(html).toContain('@media print');expect(html).toContain('page-break-inside:avoid');expect(html).toContain('Review recommended');});
it('releases new artifacts as template version 2 with frozen presentation data',async()=>{const {data}=fixture('MONITORING'),repo=new MemoryRepository(data),store=new MemoryStore(),released=await releaseReport(repo,store,'report','Operator',now+1000);expect(released).toMatchObject({customerVersion:2,customerPresentation:{version:1,kind:'Monitoring',changeCount:1,observationCompletedAt:new Date(now).toISOString()}});expect(released.hash).toMatch(/^[a-f0-9]{64}$/);expect(store.put).toHaveBeenCalledOnce();});
it('never regenerates or changes an already released historical artifact',async()=>{const {data,report}=fixture();Object.assign(report,{status:'RELEASED',customerVersion:1,artifact:'historic.html',hash:'historic-hash',releasedAt:now});const repo=new MemoryRepository(data),store=new MemoryStore(),before=JSON.stringify(data.reports[0]);const released=await releaseReport(repo,store,'report','Operator',now+1000);expect(JSON.stringify(released)).toBe(before);expect(store.put).not.toHaveBeenCalled();});
