import { expect,it } from 'vitest';
import { adjudicatePdfEvidence } from '../src/lawwatch/adjudication/index.js';
import { evidenceContext,CONTEXT_LIMIT } from '../src/lawwatch/adjudication/context.js';
import { extractAnalysisSource } from '../src/lawwatch/pdf.js';
import type { PdfExtraction } from '../src/documents/types.js';
import type { Fact,FactSet,Service } from '../src/lawwatch/types.js';
import { PDF_PRICING } from './fixtures/milestone7.js';
import {validateHumanDecisions,type HumanDecision} from '../scripts/milestone8-review.js';
const url='https://example.com/pricing.pdf',hash='a'.repeat(64);
function fixture(texts=[PDF_PRICING],title='Residential conveyancing fees'){
  const doc:PdfExtraction={documentId:'doc',requestedUrl:url,finalUrl:url,filename:'pricing.pdf',title,status:'EXTRACTED',sha256:hash,parserVersion:'pdfjs-dist@6.3.289',normalizationVersion:1,referrers:[{url:'https://example.com/',anchor:'Residential conveyancing fees'}],pages:texts.map((text,i)=>({pageNumber:i+1,text}))};
  const pages=texts.map((text,i)=>extractAnalysisSource({sourceType:'PDF',url,title,text,pageNumber:i+1,documentId:doc.documentId,sha256:hash,referrers:doc.referrers})!);
  pages.forEach(p=>{p.pricing=true;p.pricingServices=['residential_conveyancing'];});
  const raw:FactSet={schemaVersion:1,detectorVersion:'1.3',scanId:'scan',pages};return {doc,raw};
}
function candidate(text:string,snippet:string,ruleId='PRICE-001',title='Residential conveyancing fees',service:Service='residential_conveyancing'){
  const {doc,raw}=fixture([text],title);const page=raw.pages[0];page.pricingServices=[service];
  const fact:Fact={method:'fixture-candidate',snippet,confidence:'HIGH',source:{sourceType:'PDF',url,title,pageNumber:1,documentId:'doc',sha256:hash,referrers:doc.referrers}};
  page.signals={[ruleId]:[fact]};return {doc,raw,fact,page};
}
it('keeps raw extraction unchanged and produces deterministic independent assessment records',()=>{const {doc,raw}=fixture();const before=structuredClone(raw);const a=adjudicatePdfEvidence(raw,[doc]);expect(raw).toEqual(before);expect(a).toEqual(adjudicatePdfEvidence(raw,[doc]));expect(a.report.mode).toBe('deterministic');expect(a.report.counts.SUPPORTED).toBeGreaterThan(0);expect(a.report.items[0].source.referrers).toEqual(doc.referrers);});
it('bounds context and records offsets into normalized page text',()=>{const text='Residential conveyancing. '+('context '.repeat(100))+'Our fees are £900. '+('more context '.repeat(100));const {doc,fact}=candidate(text,'Our fees are £900.');const c=evidenceContext(fact,doc);expect(c.matched).toBe(true);expect(c.text.length).toBeLessThanOrEqual(CONTEXT_LIMIT);expect(c.text).toContain(fact.snippet);expect(c.end-c.start).toBe(c.text.length);});
it.each(['missing document','missing page','hash mismatch','URL mismatch','failed extraction','absent snippet'])('withholds support for %s',kind=>{const {doc,raw}=fixture();const f=raw.pages[0].signals['PRICE-001'][0];raw.pages[0].signals={'PRICE-001':[f]};if(kind==='missing page')f.source!.pageNumber=99;if(kind==='hash mismatch')doc.sha256='b'.repeat(64);if(kind==='URL mismatch')doc.finalUrl='https://example.com/other.pdf';if(kind==='failed extraction')doc.status='NO_TEXT';if(kind==='absent snippet')f.snippet='Text never present in this PDF.';const a=adjudicatePdfEvidence(raw,kind==='missing document'?[]:[doc]);expect(a.report.items.find(i=>i.ruleId==='PRICE-001')!.state).toBe('INSUFFICIENT_CONTEXT');expect(a.facts!.pages[0].signals['PRICE-001']).toBeUndefined();});
it('rejects a pricing reference explicitly assigned to another service',()=>{const {doc,raw}=candidate('We provide uncontested probate. Our fees are £900.','Our fees are £900.','PRICE-001','Probate fees');const a=adjudicatePdfEvidence(raw,[doc]);expect(a.report.items[0].state).toBe('NOT_RELEVANT');});
it('rejects mixed-service document pricing even when one page looks relevant',()=>{const {doc,raw}=fixture([PDF_PRICING,'We provide uncontested probate. Our legal fees are £500.']);const a=adjudicatePdfEvidence(raw,[doc]);expect(a.report.items.filter(i=>i.ruleId.startsWith('PRICE')).every(i=>i.state==='AMBIGUOUS')).toBe(true);});
it('keeps multiple relevant pages with distinct valid support within one service document',()=>{const {doc,raw}=fixture(['Residential conveyancing: our fees range from £900 to £1200.','Residential conveyancing: our legal fees exclude VAT at 20%.']);const a=adjudicatePdfEvidence(raw,[doc]);expect(a.report.items.find(i=>i.ruleId==='PRICE-001')!.state).toBe('SUPPORTED');expect(a.report.items.find(i=>i.ruleId==='PRICE-008')!.source.pageNumber).toBe(2);expect(a.report.items.find(i=>i.ruleId==='PRICE-008')!.state).toBe('SUPPORTED');});
it('does not combine words across pages to manufacture context',()=>{const {doc,raw}=fixture(['VAT','Residential conveyancing fees and services are described on this page.']);const a=adjudicatePdfEvidence(raw,[doc]);expect(a.report.items.filter(i=>i.source.pageNumber===1).every(i=>i.state==='INSUFFICIENT_CONTEXT')).toBe(true);});
it('treats generic complaints text in an unrelated guide as irrelevant',()=>{const {doc,raw}=candidate('The Legal Ombudsman handles complaints. You can contact the Legal Ombudsman to complain by email.','You can contact the Legal Ombudsman to complain by email.','LAW-U006','Consumer information guide');const a=adjudicatePdfEvidence(raw,[doc]);expect(a.report.items[0].state).toBe('NOT_RELEVANT');});
it('supports explicit client complaints contact in a relevant policy',()=>{const {doc,raw}=candidate('Our complaints procedure: if you are unhappy with our service you can contact the Legal Ombudsman to complain by email.','you can contact the Legal Ombudsman to complain by email.','LAW-U006','Client complaints procedure');expect(adjudicatePdfEvidence(raw,[doc]).report.items[0].state).toBe('SUPPORTED');});
it.each(['Newsletter','Case study','Impact report','Privacy policy'])('does not use an SRA number in an irrelevant %s',title=>{const {doc,raw}=candidate('Our firm is authorised and regulated by the SRA number 123456.','SRA number 123456.','LAW-U001',title);expect(adjudicatePdfEvidence(raw,[doc]).report.items[0].state).toBe('NOT_RELEVANT');});
it('requires an own-firm relationship for a number instead of its mere presence',()=>{const {doc,raw}=candidate('For information please visit the register. SRA number 123456. This is a number from the register.','SRA number 123456.','LAW-U001','Regulatory information');expect(adjudicatePdfEvidence(raw,[doc]).report.items[0].state).toBe('INSUFFICIENT_CONTEXT');});
it('supports an explicitly attributed own-firm SRA number',()=>{const {doc,raw}=candidate('Our firm is authorised and regulated by the Solicitors Regulation Authority. SRA number 123456.','SRA number 123456.','LAW-U001','Regulatory information');expect(adjudicatePdfEvidence(raw,[doc]).report.items[0].state).toBe('SUPPORTED');});
it('does not promote hypothetical examples',()=>{const {doc,raw}=candidate('Residential conveyancing illustrative example: Our fees are £900. This is an example only.','Our fees are £900.');expect(adjudicatePdfEvidence(raw,[doc]).report.items[0].state).toBe('AMBIGUOUS');});
it('withholds repeated boilerplate without local service context',()=>{const paragraph='Our legal fees include VAT at 20%. This statement is repeated on the pages of this document.';const {doc,raw}=fixture(['Residential conveyancing. '+('filler '.repeat(120))+paragraph,paragraph]);for(const p of raw.pages){const f=p.signals['PRICE-008'][0];p.signals={'PRICE-008':[{...f,snippet:paragraph}]};}const a=adjudicatePdfEvidence(raw,[doc]);expect(a.report.items.filter(i=>i.ruleId==='PRICE-008').every(i=>i.state==='AMBIGUOUS')).toBe(true);});
it('allows meaningful repeated evidence when local service context is explicit',()=>{const text='Residential conveyancing: our legal fees include VAT at 20%.';const {doc,raw}=fixture([text,text]);const a=adjudicatePdfEvidence(raw,[doc]);expect(a.report.items.filter(i=>i.ruleId==='PRICE-008').every(i=>i.state==='SUPPORTED')).toBe(true);expect(a.report.items.filter(i=>i.ruleId==='PRICE-008')).toHaveLength(2);});
it('retains partial assessment without upgrading rule-support facts',()=>{const {doc,raw}=candidate('Residential conveyancing: the electronic transfer fee is £35 plus VAT.','the electronic transfer fee is £35 plus VAT.','PRICE-008');const a=adjudicatePdfEvidence(raw,[doc]);expect(a.report.items[0].state).toBe('PARTIALLY_SUPPORTED');expect(a.facts!.pages[0].signals['PRICE-008']).toBeUndefined();});
it('does not upgrade low-confidence extraction even with surrounding context',()=>{const {doc,raw}=fixture();raw.pages[0].signals['PRICE-001'][0].confidence='MEDIUM';const a=adjudicatePdfEvidence(raw,[doc]);expect(a.report.items.find(i=>i.ruleId==='PRICE-001')!.state).toBe('PARTIALLY_SUPPORTED');});
it('leaves HTML evidence unchanged',()=>{const {doc,raw}=fixture();raw.pages[0].sourceType='HTML';expect(adjudicatePdfEvidence(raw,[doc]).facts).toEqual(raw);expect(adjudicatePdfEvidence(raw,[doc]).report.items).toEqual([]);});
it('does not label a house valuation as the firm fee',()=>{const {doc,raw}=candidate('Residential conveyancing guide: Average house prices are £300,000 in this area.','Average house prices are £300,000 in this area.');expect(adjudicatePdfEvidence(raw,[doc]).report.items[0].state).toBe('NOT_RELEVANT');});
it('distinguishes a process mention from a stage sequence',()=>{const {doc,raw}=candidate('Residential conveyancing. Our application process usually takes 6 weeks to prepare.','Our application process usually takes 6 weeks to prepare.','PRICE-013');expect(adjudicatePdfEvidence(raw,[doc]).report.items[0].state).toBe('PARTIALLY_SUPPORTED');});
it('gives empty input an explicit deterministic zero assessment',()=>{expect(adjudicatePdfEvidence(undefined,[]).report.items).toEqual([]);});
it('locates separately selected complaints clauses on the same page',()=>{const {doc,raw}=candidate('Our complaints procedure. Contact our partner to complain. We acknowledge your letter. We investigate your complaint and respond.','Contact our partner to complain. We investigate your complaint and respond.','LAW-U004','Client complaints procedure');raw.pages[0].signals['LAW-U004'][0].method='client-complaints-process';const a=adjudicatePdfEvidence(raw,[doc]);expect(a.report.items[0].state).toBe('SUPPORTED');expect(a.report.items[0].context.locationMethod).toBe('verified-clauses');expect(a.report.items[0].context.text).toContain('We acknowledge your letter.');});
it('retains explicit average-fee VAT support',()=>{const {doc,raw}=candidate('Residential conveyancing: an average charge for this work is £900 plus 20% VAT.','an average charge for this work is £900 plus 20% VAT.','PRICE-009');expect(adjudicatePdfEvidence(raw,[doc]).report.items[0].state).toBe('SUPPORTED');});
it('never silently drops a short unverified clause from compound evidence',()=>{const {doc,raw}=candidate('Our complaints procedure: contact our partner to complain. We investigate and respond to your complaint.','Missing. contact our partner to complain. We investigate and respond to your complaint.','LAW-U004','Client complaints procedure');raw.pages[0].signals['LAW-U004'][0].method='client-complaints-process';expect(adjudicatePdfEvidence(raw,[doc]).report.items[0].state).toBe('INSUFFICIENT_CONTEXT');});
it('keeps human decisions separate from machine assessments',()=>{const {doc,raw}=fixture();const items=adjudicatePdfEvidence(raw,[doc]).report.items;const before=structuredClone(items);const decisions:HumanDecision[]=[{itemId:items[0].id,state:'AMBIGUOUS',reviewer:'Fixture reviewer',reviewerKind:'human',reason:'Fixture-only decision',reviewedAt:'2026-09-14T00:00:00Z'}];expect(validateHumanDecisions(items,decisions).reviewed).toBe(1);expect(items).toEqual(before);});
it.each(['unknown','duplicate','reviewer','date','reason','kind'])('rejects invalid human review input: %s',kind=>{const {doc,raw}=fixture();const items=adjudicatePdfEvidence(raw,[doc]).report.items;const d:HumanDecision={itemId:items[0].id,state:'SUPPORTED',reviewer:'Fixture reviewer',reviewerKind:'human',reason:'Fixture only',reviewedAt:'2026-09-14T00:00:00Z'};if(kind==='unknown')d.itemId='unknown';if(kind==='reviewer')d.reviewer='';if(kind==='date')d.reviewedAt='invalid';if(kind==='reason')d.reason='';if(kind==='kind')(d as {reviewerKind:string}).reviewerKind='machine';expect(()=>validateHumanDecisions(items,kind==='duplicate'?[d,d]:[d])).toThrow();});
