import {readFile,readdir,writeFile,mkdir} from 'node:fs/promises';
import {join} from 'node:path';
import type {LawReport} from '../src/lawwatch/types.js';
const read=async(p:string)=>JSON.parse(await readFile(p,'utf8'));
const baseline=await read('reports/milestone8/release/summary.json'),preserved=await read('reports/milestone9/corrected/summary.json'),queue=await read('reports/milestone9/review-ready/queue.json'),comparison=await read('reports/milestone9/clive-review-after-comparison.json');
const changes=[];for(const file of(await readdir('reports/milestone9/corrected')).filter(f=>f.endsWith('.report.json'))){const before=await read(join('reports/milestone8/release',file)) as LawReport,after=await read(join('reports/milestone9/corrected',file)) as LawReport;
  for(const r of after.results){const old=before.results.find(b=>b.ruleId===r.ruleId&&b.serviceType===r.serviceType&&b.resource===r.resource);if(!old||old.status!==r.status)changes.push({site:after.site,rule:r.ruleId,service:r.serviceType,before:old?.status??'NO_MATCH',after:r.status});}}
let fresh;try{fresh=await read('reports/milestone9/live/summary.json');}catch{}
const beforeReview=await read('reports/milestone9/clive-review-comparison.json');
const freshReplay=await read('reports/milestone9/live-corrected/summary.json');
const output={schemaVersion:1,status:'VALIDATED',productionCorrections:3,humanReviewedDisagreementsFixed:3,benchmarkSha256:preserved.benchmarkSha256,m8:baseline.m8.overall,preserved:preserved.m8.overall,ruleResultsChanged:changes.length,supportedToUnknown:changes.filter(c=>c.before==='PASS'&&c.after==='UNKNOWN').length,unknownToSupported:changes.filter(c=>c.before==='UNKNOWN'&&c.after==='PASS').length,changes,pdfAssessments:{...preserved.adjudication,independentHumanReviews:66,reviewScope:'66 sampled PDF items, plus 12 separate HTML controls'},serious:preserved.serious,review:{before:beforeReview,after:comparison,sampleSize:queue.sampleSize,firms:new Set(queue.items.map((i:{firm:string})=>i.firm)).size,coverage:queue.coverage,humanReviewed:comparison.humanReviewed,exactAgreement:comparison.exactAgreement,falseSupportRate:comparison.falseSupportRate,falseRejectionRate:comparison.falseRejectionRate},freshPolicyReplay:freshReplay,fresh:fresh?{completed:fresh.completed,metrics:fresh.fresh.overall,preservedSameFirms:fresh.preservedSameFirms.overall,sites:fresh.rows.map((r:any)=>({firm:r.firm,completedAt:r.completedAt,durationMs:r.durationMs,pagesScanned:r.coverage.pagesScanned,pagesFailed:r.coverage.pagesFailed,pdf:r.pdf,metrics:r.evaluation.metrics}))}:null};
await mkdir('docs/Validation/milestone9',{recursive:true});await writeFile('docs/Validation/milestone9/final-summary.json',JSON.stringify(output,null,2)+'\n');console.log(JSON.stringify(output,null,2));
