import { validatePack } from '../rules/pack.js';
import type { Rule,RulePack } from '../rules/types.js';
export const LAW_PACK_ID='lawwatch-england-wales';
export const REGULATORY_REFERENCE='https://www.sra.org.uk/solicitors/standards-regulations/transparency-rules/';
export const DRIFT_AGE_YEARS=3;
const universal=['SRA number detectable','SRA digital badge detectable','SRA digital badge operation','Complaints procedure located','Legal Ombudsman information located','Legal Ombudsman complaint contact explained','Legal Ombudsman referral timing explained','SRA complaints / conduct route located','SRA escalation wording detected','Regulatory information accessible'];
const pricing=['Cost or cost range provided','Charging basis explained','Hourly or fixed-fee information','Experience / qualifications of people carrying out work','Supervisor experience / qualifications','Likely disbursements identified','Disbursement costs provided','VAT treatment of fees','VAT amount or rate on fees','VAT treatment of disbursements','Services included in price','Expected exclusions described','Key stages described','Typical timescales described','Conditional-fee customer payments','Pricing structurally accessible','Pricing associated with service'];
const changes=['Monitored pricing page availability','Monitored complaints page availability','Previously detected SRA number continuity','Previously detected digital badge continuity','Material pricing content change'];
function definitions(prefix:string,names:string[],category:string,severity:Rule['severity']):Rule[] {
  return names.map((name,i)=>({schemaVersion:1,id:`${prefix}${String(i+1).padStart(3,'0')}`,name,description:name,category,severity:prefix==='LAW-U'&&i===9||prefix==='LAW-C'&&i===4?'MEDIUM':severity,version:'1.3',engineVersion:'1',enabled:true,applicability:'always',detector:'structured_fact',configuration:{signal:`${prefix}${String(i+1).padStart(3,'0')}`},evidenceRequirements:['source URL','selected snippet or structured observation','current scan identity'],resultMapping:{healthy:'PASS',changed:'WARNING'},documentation:`Website indicators only. SRA Transparency Rules, current version effective 11 April 2025, checked 12 September 2026: ${REGULATORY_REFERENCE}. Static limitations do not establish absence. Detector version 1.3.`,packId:LAW_PACK_ID}));
}
export const lawPack:RulePack=validatePack({schemaVersion:1,id:LAW_PACK_ID,name:'LawWatch England & Wales',version:'1.3',description:'Conservative deterministic public website signals associated with SRA Transparency Rules',engineVersion:'1',rules:[...definitions('LAW-U',universal,'regulatory','HIGH'),...definitions('PRICE-',pricing,'pricing','HIGH'),...definitions('LAW-I',['Old explicit review/update year','Historic pricing year reference'],'drift','INFO').map(r=>({...r,configuration:{...r.configuration,threshold:DRIFT_AGE_YEARS}})),...definitions('LAW-C',changes,'monitoring','HIGH')]});
