import { adjudicationSchema } from './adjudication/schema.js';
import { resultSchema } from '../rules/json-schema.js';
import { STATES } from '../rules/types.js';
import { SERVICE_IDS,UNKNOWN_REASONS } from './types.js';
import { pdfReportSchema,pdfProvenanceSchema,pdfReferrersSchema } from '../documents/schema.js';
import { PDF_STATUSES } from '../documents/types.js';
const text={type:'string'};
const browserSummary={type:'object',required:['attempted','rendered','failed','timedOut','limitReached','addedTimeMs','statement'],properties:{...Object.fromEntries(['attempted','rendered','failed','timedOut','limitReached','addedTimeMs'].map(k=>[k,{type:'number',minimum:0}])),statement:text},additionalProperties:false};
const renderedOrigin={type:'object',required:['sourceType','url','requestedUrl','observedAt','domHash','staticHash','strategy'],properties:{sourceType:{const:'RENDERED_DOM'},url:text,requestedUrl:text,observedAt:{type:'string',format:'date-time'},domHash:text,staticHash:text,strategy:{const:'initial-visible-dom-v1'}},additionalProperties:false};
const fact={type:'object',required:['method','snippet','confidence'],properties:{observation:renderedOrigin,source:pdfProvenanceSchema,method:text,snippet:{type:'string',maxLength:240},value:text,confidence:{enum:['HIGH','MEDIUM','LOW']}},additionalProperties:false};
const classification={type:'object',required:['service','state','evidence','sourceUrls','origin','explanation'],properties:{service:{enum:SERVICE_IDS},state:{enum:['DETECTED_HIGH_CONFIDENCE','DETECTED_LOW_CONFIDENCE','NOT_DETECTED','UNKNOWN']},evidence:{type:'array',items:fact},sourceUrls:{type:'array',items:text},excluded:{type:'boolean'},origin:{enum:['detector','override']},explanation:text},additionalProperties:false};
const lawResult={type:'object',required:resultSchema.required,properties:{...resultSchema.properties,serviceType:{enum:SERVICE_IDS},unknownReasonCodes:{type:'array',items:{enum:UNKNOWN_REASONS},minItems:1}},additionalProperties:false};
export const lawReportSchema={
  $schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:watchlayer:lawwatch-report:1',type:'object',additionalProperties:false,
  required:['schemaVersion','site','scanId','packId','packVersion','universalResults','classifications','inventory','results','changes','drift','summary','runs','statement'],
  properties:{browser:browserSummary,adjudication:adjudicationSchema,pdf:pdfReportSchema,schemaVersion:{const:1},site:text,scanId:text,packId:{const:'lawwatch-england-wales'},packVersion:{enum:['1.0','1.1','1.2','1.3','1.4','1.5','1.6','1.7','1.8']},universalResults:{type:'array',items:resultSchema},classifications:{type:'array',items:classification},
    inventory:{type:'array',items:{type:'object',required:['signal','url','type','confidence','firstObserved','latestObserved','observationState','sourceEvidence'],properties:{document:{type:'object',required:['documentId','status','referrers'],properties:{documentId:text,status:{enum:PDF_STATUSES},title:text,pageCount:{type:'integer',minimum:0},referrers:pdfReferrersSchema,sha256:text},additionalProperties:false},signal:text,service:{enum:SERVICE_IDS},url:text,type:{enum:['page','document']},confidence:{enum:['HIGH','MEDIUM','LOW']},firstObserved:{type:'string',format:'date-time'},latestObserved:{type:'string',format:'date-time'},observationState:{enum:['observed','not_observed','confirmed_missing']},sourceEvidence:{type:'array',items:{type:'object',required:['url','facts'],properties:{url:text,facts:{type:'array',items:fact},clickDepth:{type:['integer','null'],minimum:0},link:{type:'object',required:['url','label','region','document'],properties:{url:text,label:text,region:{enum:['navigation','footer','body']},document:{type:'boolean'},sourceUrl:text,nearbyContext:{type:'string',maxLength:240},services:{type:'array',items:{enum:SERVICE_IDS}},purpose:{enum:['pricing','complaints']},associationConfidence:{enum:['HIGH','MEDIUM','LOW']}},additionalProperties:false}},additionalProperties:false}}},additionalProperties:false}},
    results:{type:'array',items:lawResult},changes:{type:'array',items:lawResult},drift:{type:'array',items:lawResult},summary:{type:'object',required:STATES,properties:Object.fromEntries(STATES.map(s=>[s,{type:'integer',minimum:0}])),additionalProperties:false},runs:{type:'array',minItems:2,items:{type:'object',required:['schemaVersion','runId','scanId','packId','packVersion','definition','results','findings'],properties:{schemaVersion:{const:1},runId:text,scanId:text,packId:text,packVersion:text,definition:{type:'object'},results:{type:'array',items:lawResult},findings:{type:'array',items:{type:'object'}}}}},statement:text},
};
