import { resultSchema } from '../rules/json-schema.js';
import { STATES } from '../rules/types.js';
import { SERVICE_IDS } from './types.js';
const text={type:'string'};
const fact={type:'object',required:['method','snippet','confidence'],properties:{method:text,snippet:{type:'string',maxLength:240},value:text,confidence:{enum:['HIGH','MEDIUM','LOW']}},additionalProperties:false};
const classification={type:'object',required:['service','state','evidence','sourceUrls','origin','explanation'],properties:{service:{enum:SERVICE_IDS},state:{enum:['DETECTED_HIGH_CONFIDENCE','DETECTED_LOW_CONFIDENCE','NOT_DETECTED','UNKNOWN']},evidence:{type:'array',items:fact},sourceUrls:{type:'array',items:text},excluded:{type:'boolean'},origin:{enum:['detector','override']},explanation:text},additionalProperties:false};
const lawResult={type:'object',required:resultSchema.required,properties:{...resultSchema.properties,serviceType:{enum:SERVICE_IDS}},additionalProperties:false};
export const lawReportSchema={
  $schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:watchlayer:lawwatch-report:1',type:'object',additionalProperties:false,
  required:['schemaVersion','site','scanId','packId','packVersion','universalResults','classifications','inventory','results','changes','drift','summary','runs','statement'],
  properties:{schemaVersion:{const:1},site:text,scanId:text,packId:{const:'lawwatch-england-wales'},packVersion:{const:'1.0'},universalResults:{type:'array',items:resultSchema},classifications:{type:'array',items:classification},
    inventory:{type:'array',items:{type:'object',required:['signal','url','type','confidence','firstObserved','latestObserved','observationState','sourceEvidence'],properties:{signal:text,service:{enum:SERVICE_IDS},url:text,type:{enum:['page','document']},confidence:{enum:['HIGH','MEDIUM','LOW']},firstObserved:{type:'string',format:'date-time'},latestObserved:{type:'string',format:'date-time'},observationState:{enum:['observed','not_observed','confirmed_missing']},sourceEvidence:{type:'array',items:{type:'object',required:['url','facts'],properties:{url:text,facts:{type:'array',items:fact},clickDepth:{type:['integer','null'],minimum:0},link:{type:'object',required:['url','label','region','document'],properties:{url:text,label:text,region:{enum:['navigation','footer','body']},document:{type:'boolean'}},additionalProperties:false}},additionalProperties:false}}},additionalProperties:false}},
    results:{type:'array',items:lawResult},changes:{type:'array',items:lawResult},drift:{type:'array',items:lawResult},summary:{type:'object',required:STATES,properties:Object.fromEntries(STATES.map(s=>[s,{type:'integer',minimum:0}])),additionalProperties:false},runs:{type:'array',minItems:2,items:{type:'object',required:['schemaVersion','runId','scanId','packId','packVersion','definition','results','findings'],properties:{schemaVersion:{const:1},runId:text,scanId:text,packId:text,packVersion:text,definition:{type:'object'},results:{type:'array',items:lawResult},findings:{type:'array',items:{type:'object'}}}}},statement:text},
};
